#define ___(id, ident, ...)         case id: op##ident(__VA_ARGS__); break;
#define __M(id, ident, inst)        case id: p.m ? op##ident<true, inst>() : op##ident<false, inst>(); break;
#define i_M(id, ident, inst, index) case id: p.m ? op##ident<true, inst, index>() : op##ident<false, inst, index>(); break;
#define __X(id, ident, inst)        case id: p.x ? op##ident<true, inst>() : op##ident<false, inst>(); break;
#define i_X(id, ident, inst, index) case id: p.x ? op##ident<true, inst, index>() : op##ident<false, inst, index>(); break;

    ___(0x00, BRK)
    __M(0x01, IndexedIndirect, ORA)
    ___(0x02, COP)
    __M(0x03, StackRelative, ORA)
    __M(0x04, ModifyDirect, TSB)
    __M(0x05, Direct, ORA)
    __M(0x06, ModifyDirect, ASL)
    __M(0x07, IndirectLong, ORA)
    ___(0x08, PHP)
    __M(0x09, Immediate, ORA)
    __M(0x0a, Implied, ASL)
    ___(0x0b, PHD)
    __M(0x0c, ModifyAbsolute, TSB)
    __M(0x0d, Absolute, ORA)
    __M(0x0e, ModifyAbsolute, ASL)
    __M(0x0f, Long, ORA)
    ___(0x10, Branch, !p.n)
    i_M(0x11, Indirect, ORA, INDEX_Y)
    __M(0x12, Indirect, ORA)
    i_M(0x13, StackRelativeIndirect, ORA, INDEX_Y)
    __M(0x14, ModifyDirect, TRB)
    i_M(0x15, Direct, ORA, INDEX_X)
    i_M(0x16, ModifyDirect, ASL, INDEX_X)
    i_M(0x17, IndirectLong, ORA, INDEX_Y)
    ___(0x18, Clear, p.c)
    i_M(0x19, Absolute, ORA, INDEX_Y)
    __M(0x1a, Implied, INC)
    ___(0x1b, TCS)
    __M(0x1c, ModifyAbsolute, TRB)
    i_M(0x1d, Absolute, ORA, INDEX_X)
    i_M(0x1e, ModifyAbsolute, ASL, INDEX_X)
    i_M(0x1f, Long, ORA, INDEX_X)
    ___(0x20, JSR)
    __M(0x21, IndexedIndirect, AND)
    ___(0x22, JSL)
    __M(0x23, StackRelative, AND)
    __M(0x24, Direct, BIT)
    __M(0x25, Direct, AND)
    __M(0x26, ModifyDirect, ROL)
    __M(0x27, IndirectLong, AND)
    ___(0x28, PLP)
    __M(0x29, Immediate, AND)
    __M(0x2a, Implied, ROL)
    ___(0x2b, PLD)
    __M(0x2c, Absolute, BIT)
    __M(0x2d, Absolute, AND)
    __M(0x2e, ModifyAbsolute, ROL)
    __M(0x2f, Long, AND)
    ___(0x30, Branch, p.n)
    i_M(0x31, Indirect, AND, INDEX_Y)
    __M(0x32, Indirect, AND)
    i_M(0x33, StackRelativeIndirect, AND, INDEX_Y)
    i_M(0x34, Direct, BIT, INDEX_X)
    i_M(0x35, Direct, AND, INDEX_X)
    i_M(0x36, ModifyDirect, ROL, INDEX_X)
    i_M(0x37, IndirectLong, AND, INDEX_Y)
    ___(0x38, Set, p.c)
    i_M(0x39, Absolute, AND, INDEX_Y)
    __M(0x3a, Implied, DEC)
    ___(0x3b, TSC)
    i_M(0x3c, Absolute, BIT, INDEX_X)
    i_M(0x3d, Absolute, AND, INDEX_X)
    i_M(0x3e, ModifyAbsolute, ROL, INDEX_X)
    i_M(0x3f, Long, AND, INDEX_X)
    ___(0x40, RTI)
    __M(0x41, IndexedIndirect, EOR)
    ___(0x42, WDM)
    __M(0x43, StackRelative, EOR)
    __X(0x44, Move, false) // MVP
    __M(0x45, Direct, EOR)
    __M(0x46, ModifyDirect, LSR)
    __M(0x47, IndirectLong, EOR)
    __M(0x48, Push, STA)
    __M(0x49, Immediate, EOR)
    __M(0x4a, Implied, LSR)
    ___(0x4b, PHK)
    ___(0x4c, JmpAbsolute)
    __M(0x4d, Absolute, EOR)
    __M(0x4e, ModifyAbsolute, LSR)
    __M(0x4f, Long, EOR)
    ___(0x50, Branch, !p.v)
    i_M(0x51, Indirect, EOR, INDEX_Y)
    __M(0x52, Indirect, EOR)
    i_M(0x53, StackRelativeIndirect, EOR, INDEX_Y)
    __X(0x54, Move, true) // MVN
    i_M(0x55, Direct, EOR, INDEX_X)
    i_M(0x56, ModifyDirect, LSR, INDEX_X)
    i_M(0x57, IndirectLong, EOR, INDEX_Y)
    ___(0x58, Clear, p.i)
    i_M(0x59, Absolute, EOR, INDEX_Y)
    __X(0x5a, Push, STY)
    ___(0x5b, TCD)
    ___(0x5c, JmpAbsoluteLong)
    i_M(0x5d, Absolute, EOR, INDEX_X)
    i_M(0x5e, ModifyAbsolute, LSR, INDEX_X)
    i_M(0x5f, Long, EOR, INDEX_X)
    ___(0x60, RTS)
    __M(0x61, IndexedIndirect, ADC)
    ___(0x62, Per)
    __M(0x63, StackRelative, ADC)
    __M(0x64, Direct, STZ)
    __M(0x65, Direct, ADC)
    __M(0x66, ModifyDirect, ROR)
    __M(0x67, IndirectLong, ADC)
    __M(0x68, Pull, STA)
    __M(0x69, Immediate, ADC)
    __M(0x6a, Implied, ROR)
    ___(0x6b, RTL)
    ___(0x6c, JmpIndirect<false>)
    __M(0x6d, Absolute, ADC)
    __M(0x6e, ModifyAbsolute, ROR)
    __M(0x6f, Long, ADC)
    ___(0x70, Branch, p.v)
    i_M(0x71, Indirect, ADC, INDEX_Y)
    __M(0x72, Indirect, ADC)
    i_M(0x73, StackRelativeIndirect, ADC, INDEX_Y)
    i_M(0x74, Direct, STZ, INDEX_X)
    i_M(0x75, Direct, ADC, INDEX_X)
    i_M(0x76, ModifyDirect, ROR, INDEX_X)
    i_M(0x77, IndirectLong, ADC, INDEX_Y)
    ___(0x78, Set, p.i)
    i_M(0x79, Absolute, ADC, INDEX_Y)
    __X(0x7a, Pull, STY)
    ___(0x7b, TDC)
    ___(0x7c, JmpAbsIndexedIndirect<false>)
    i_M(0x7d, Absolute, ADC, INDEX_X)
    i_M(0x7e, ModifyAbsolute, ROR, INDEX_X)
    i_M(0x7f, Long, ADC, INDEX_X)
    ___(0x80, Branch, true)
    __M(0x81, IndexedIndirect, STA)
    ___(0x82, BranchLong)
    __M(0x83, StackRelative, STA)
    __X(0x84, Direct, STY)
    __M(0x85, Direct, STA)
    __X(0x86, Direct, STX)
    __M(0x87, IndirectLong, STA)
    i_X(0x88, Implied, DEC, INDEX_Y)
    __M(0x89, Immediate, BIT_IM)
    ___(0x8a, TXA)
    ___(0x8b, PHB)
    __X(0x8c, Absolute, STY)
    __M(0x8d, Absolute, STA)
    __X(0x8e, Absolute, STX)
    __M(0x8f, Long, STA)
    ___(0x90, Branch, !p.c)
    i_M(0x91, Indirect, STA, INDEX_Y)
    __M(0x92, Indirect, STA)
    i_M(0x93, StackRelativeIndirect, STA, INDEX_Y)
    i_X(0x94, Direct, STY, INDEX_X)
    i_M(0x95, Direct, STA, INDEX_X)
    i_X(0x96, Direct, STX, INDEX_Y)
    i_M(0x97, IndirectLong, STA, INDEX_Y)
    ___(0x98, TYA)
    i_M(0x99, Absolute, STA, INDEX_Y)
    ___(0x9a, TXS)
    ___(0x9b, TXY)
    __M(0x9c, Absolute, STZ)
    i_M(0x9d, Absolute, STA, INDEX_X)
    i_M(0x9e, Absolute, STZ, INDEX_X)
    i_M(0x9f, Long, STA, INDEX_X)
    __X(0xa0, Immediate, LDY)
    __M(0xa1, IndexedIndirect, LDA)
    __X(0xa2, Immediate, LDX)
    __M(0xa3, StackRelative, LDA)
    __X(0xa4, Direct, LDY)
    __M(0xa5, Direct, LDA)
    __X(0xa6, Direct, LDX)
    __M(0xa7, IndirectLong, LDA)
    ___(0xa8, TAY)
    __M(0xa9, Immediate, LDA)
    ___(0xaa, TAX)
    ___(0xab, PLB)
    __X(0xac, Absolute, LDY)
    __M(0xad, Absolute, LDA)
    __X(0xae, Absolute, LDX)
    __M(0xaf, Long, LDA)
    ___(0xb0, Branch, p.c)
    i_M(0xb1, Indirect, LDA, INDEX_Y)
    __M(0xb2, Indirect, LDA)
    i_M(0xb3, StackRelativeIndirect, LDA, INDEX_Y)
    i_X(0xb4, Direct, LDY, INDEX_X)
    i_M(0xb5, Direct, LDA, INDEX_X)
    i_X(0xb6, Direct, LDX, INDEX_Y)
    i_M(0xb7, IndirectLong, LDA, INDEX_Y)
    ___(0xb8, Clear, p.v)
    i_M(0xb9, Absolute, LDA, INDEX_Y)
    ___(0xba, TSX)
    ___(0xbb, TYX)
    i_X(0xbc, Absolute, LDY, INDEX_X)
    i_M(0xbd, Absolute, LDA, INDEX_X)
    i_X(0xbe, Absolute, LDX, INDEX_Y)
    i_M(0xbf, Long, LDA, INDEX_X)
    __X(0xc0, Immediate, CPY)
    __M(0xc1, IndexedIndirect, CMP)
    ___(0xc2, ResetP)
    __M(0xc3, StackRelative, CMP)
    __X(0xc4, Direct, CPY)
    __M(0xc5, Direct, CMP)
    __M(0xc6, ModifyDirect, DEC)
    __M(0xc7, IndirectLong, CMP)
    i_X(0xc8, Implied, INC, INDEX_Y)
    __M(0xc9, Immediate, CMP)
    i_X(0xca, Implied, DEC, INDEX_X)
    ___(0xcb, Wait)
    __X(0xcc, Absolute, CPY)
    __M(0xcd, Absolute, CMP)
    __M(0xce, ModifyAbsolute, DEC)
    __M(0xcf, Long, CMP)
    ___(0xd0, Branch, !p.z)
    i_M(0xd1, Indirect, CMP, INDEX_Y)
    __M(0xd2, Indirect, CMP)
    i_M(0xd3, StackRelativeIndirect, CMP, INDEX_Y)
    ___(0xd4, PushEffectiveIndirectAddress)
    i_M(0xd5, Direct, CMP, INDEX_X)
    i_M(0xd6, ModifyDirect, DEC, INDEX_X)
    i_M(0xd7, IndirectLong, CMP, INDEX_Y)
    ___(0xd8, Clear, p.d)
    i_M(0xd9, Absolute, CMP, INDEX_X)
    __X(0xda, Push, STX)
    ___(0xdb, Stop)
    ___(0xdc, JmpIndirect<true>)
    i_M(0xdd, Absolute, CMP, INDEX_X)
    i_M(0xde, ModifyAbsolute, DEC, INDEX_X)
    i_M(0xdf, Long, CMP, INDEX_X)
    __X(0xe0, Immediate, CPX)
    __M(0xe1, IndexedIndirect, SBC)
    ___(0xe2, SetP)
    __M(0xe3, StackRelative, SBC)
    __X(0xe4, Direct, CPX)
    __M(0xe5, Direct, SBC)
    __M(0xe6, ModifyDirect, INC)
    __M(0xe7, IndirectLong, SBC)
    i_X(0xe8, Implied, INC, INDEX_X)
    __M(0xe9, Immediate, SBC)
    ___(0xea, NOP)
    ___(0xeb, XBA)
    __X(0xec, Absolute, CPX)
    __M(0xed, Absolute, SBC)
    __M(0xee, ModifyAbsolute, INC)
    __M(0xef, Long, SBC)
    ___(0xf0, Branch, p.z)
    i_M(0xf1, Indirect, SBC, INDEX_Y)
    __M(0xf2, Indirect, SBC)
    i_M(0xf3, StackRelativeIndirect, SBC, INDEX_Y)
    ___(0xf4, PushEffectiveAddress)
    i_M(0xf5, Direct, SBC, INDEX_X)
    i_M(0xf6, ModifyDirect, INC, INDEX_X)
    i_M(0xf7, IndirectLong, SBC, INDEX_Y)
    ___(0xf8, Set, p.d)
    i_M(0xf9, Absolute, SBC, INDEX_Y)
    __X(0xfa, Pull, STX)
    ___(0xfb, XCE)
    ___(0xfc, JmpAbsIndexedIndirect<true>)
    i_M(0xfd, Absolute, SBC, INDEX_X)
    i_M(0xfe, ModifyAbsolute, INC, INDEX_X)
    i_M(0xff, Long, SBC, INDEX_X)
