
branches:
  only:
    - master
    - /v\d*\.\d*/
    - /v\d*\.\d*\.\d*/
    - travis_integration

dist: focal

matrix:
  include:
    - compiler: gcc
      addons: true

before_install:
  - sudo apt-get -q update

addons:
  apt:
    packages:
      - g++-12
      - cmake
      - mesa-common-dev
      - libgtk-3-dev
      - libopenal-dev
      - libpulse-dev
      - libudev-dev
      - sshpass


script:
  - cmake -B builds/release
  - cmake --build builds/release -j 2
  - cd data
  - chmod +x build_deb.sh
  - ./build_deb.sh
  - dpkg-deb --build ./denisepackage
  - tar -zcf denisepackage.tar.gz denisepackage.deb

deploy:
  provider: script
  script:
    - |
      export gzTarget=denisepackage.tar.gz
# todo
  on:
    tags: false