
branches:
  only:
    - master
    - /v\d*\.\d*/
    - /v\d*\.\d*\.\d*/

language: generic
dist: jammy
os: linux

cache:
   directories:
   - $HOME/.flatpak-builder

before_install:
# jammy update flatpak-builder only to version 1.2.x. However, we need a more recent version to avoid an error: "bwrap: execvp appstream-compose: No such file"
  - sudo add-apt-repository -y ppa:flatpak/stable
  - sudo apt-get -q update
  - sudo apt-get -f install flatpak-builder
  - flatpak-builder --version

addons:
  apt:
    packages:
      - g++-12
      - cmake
      - mesa-common-dev
      - libgtk-3-dev
      - libpulse-dev
      - libudev-dev
      - libxcb-xinput-dev
      - libxcb-xfixes0
      - sshpass      
      #- flatpak-builder
      - libusb-1.0-0-dev
      - libmp3lame-dev

jobs:
  include:
    - name: Flatpak
      compiler: gcc
      script:
      - flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - flatpak-builder --force-clean --verbose=0 --user --install-deps-from=flathub --repo=repo .flatpak-builder/out data/org.bitbucket.Denise.yml
      - flatpak build-bundle repo denise.flatpak org.bitbucket.Denise --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
      - |
        if [[ $TRAVIS_BRANCH =~ v[0-999].[0-999] || $TRAVIS_BRANCH =~ v[0-999].[0-999].[0-999] ]]; then
          export deployFile=denise_$TRAVIS_BRANCH.flatpak
          export deployTarget=${FTP_TAGS}
        else
          export deployFile=denise_$(echo ${TRAVIS_COMMIT} | cut -c 1-7).flatpak
          export deployTarget=${FTP_NIGHTLIES}
        fi
      - mv denise.flatpak "${deployFile}"


    - name: DEB package    
      compiler: gcc
      script:
      - cmake -B builds/release -DCMAKE_CXX_COMPILER=g++-12 || travis_terminate 1;
      - cmake --build builds/release -j 4 || travis_terminate 1;
      - cd data
      - chmod +x build_deb.sh
      - ./build_deb.sh
      - dpkg-deb --build ./denisepackage || travis_terminate 1;
      - |
        if [[ $TRAVIS_BRANCH =~ v[0-999].[0-999] || $TRAVIS_BRANCH =~ v[0-999].[0-999].[0-999] ]]; then
          export deployFile=denise_ubuntu2004_$TRAVIS_BRANCH.deb
          export deployTarget=${FTP_TAGS}
        else
          export deployFile=denise_ubuntu2004_$(echo ${TRAVIS_COMMIT} | cut -c 1-7).deb
          export deployTarget=${FTP_NIGHTLIES}
        fi
      - mv denisepackage.deb "${deployFile}"

after_success:
  - echo ${FTP_PSW} > ftp.txt 2>&1

deploy:
  provider: script
  script: sshpass -f "ftp.txt" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${deployFile}" piciji@frs.sourceforge.net:"${deployTarget}"
  edge: true
  on:
    all_branches: true


# hint for env FTP_TAGS: v\\\ 1.0