
version: '{build}'

skip_commits:
  files:
    - data/*
    - '**/*.md'

image:
  - Visual Studio 2019

environment:
  matrix:      
    - OS: win64 
      MINGW_DIR: mingw64      
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
      MINGW_ARCHIVE: x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
      MINGW_LIBS: '%MINGW_DIR%\x86_64-w64-mingw32' 
    - OS: win32
      MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
      MINGW_ARCHIVE: i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
      MINGW_LIBS:  '%MINGW_DIR%\i686-w64-mingw32'
      
install:
  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  
before_build:
  - set Path=%CD%\%MINGW_DIR%\bin;%Path%     
  - cmd: xcopy /I /Y /S "data\libs\include" "%MINGW_LIBS%\include"
  - cmd: xcopy /I /Y "data\libs\shared\%OS%\OpenAL32.lib" "%MINGW_LIBS%\lib"
  - cmd: xcopy /I /Y "data\libs\static\%OS%\libfreetype.a" "%MINGW_LIBS%\lib"
  - cmd: del out\.gitkeep
  
build_script:
  - cmd: mingw32-make && mingw32-make install
  
artifacts:
  - path: out
    name: 'Denise_%OS%'
    type: zip
     
cache:
  - '%MINGW_ARCHIVE%'