
version: '{build}'

skip_commits:
  files:
    - 'data/**/*'
    - '**/*.md'

image:
  - Visual Studio 2019
  - macos-bigsur
  - macos
  - Ubuntu2004

stack: python 3.8
  
branches:
  only:
    - master
    - /v\d*\.\d*/
    - /v\d*\.\d*\.\d*/
    - new_shader
  
environment:
  matrix:
    - Job: macOS ARM 64-bit
      Target: macos-arm
    - Job: macOS 64-bit
      Target: macos
    - Job: Linux 64-bit
      Target: linux
    - Job: Windows 64-bit
      Target: win64
    - Job: Windows 32-bit
      Target: win32

matrix:
  exclude:
    - image: Visual Studio 2019
      Target: linux
    - image: Visual Studio 2019
      Target: macos
    - image: Visual Studio 2019
      Target: macos-arm
    - image: Ubuntu2004
      Target: win64
    - image: Ubuntu2004
      Target: win32
    - image: Ubuntu2004
      Target: macos
    - image: Ubuntu2004
      Target: macos-arm
    - image: macos
      Target: win64
    - image: macos
      Target: win32
    - image: macos
      Target: linux
    - image: macos
      Target: macos-arm
    - image: macos-bigsur
      Target: win64
    - image: macos-bigsur
      Target: win32
    - image: macos-bigsur
      Target: linux
    - image: macos-bigsur
      Target: macos
for:
-    
  matrix:
    only:
      - image: Visual Studio 2019        
      
  init:
    - if "%Target%"=="win64" ( set mingw_archive=x86_64-12.2.0-release-posix-seh-msvcrt-rt_v10-rev2.7z)
    - if "%Target%"=="win32" ( set mingw_archive=i686-12.2.0-release-posix-dwarf-msvcrt-rt_v10-rev2.7z)
    - if "%Target%"=="win64" ( set mingw_dir=mingw64)
    - if "%Target%"=="win32" ( set mingw_dir=mingw32)
    - if "%Target%"=="win64" ( set mingw_libs=%mingw_dir%\x86_64-w64-mingw32)
    - if "%Target%"=="win32" ( set mingw_libs=%mingw_dir%\i686-w64-mingw32)
    - if "%Target%"=="win64" ( set mingw_url=https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/%mingw_archive%)
    - if "%Target%"=="win32" ( set mingw_url=https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/%mingw_archive%)
    - if "%Target%"=="win64" ( set arch=x64)
    - if "%Target%"=="win32" ( set arch=x86)

  cache:
    - '%mingw_archive%'
      
  install:  
    - if not exist "%mingw_archive%" appveyor DownloadFile "%mingw_url%" -FileName "%mingw_archive%"
    - 7z x -y "%mingw_archive%" > nul
  
  before_build:  
    - set Path=%CD%\%mingw_dir%\bin;%Path%
    - cmd: xcopy /I /Y /S "data\libs\include" "%mingw_libs%\include"
    - cmd: xcopy /I /Y "data\libs\static\%arch%\libfreetype.a" "%mingw_libs%\lib"
    - cmd: del out\.gitkeep
    - cmd: g++ -v
  
  build_script:
    - cmd: mingw32-make SubSystem=win32 && mingw32-make SubSystem=win32 install
   
  after_build:
    - ps: |
        if($env:APPVEYOR_REPO_TAG -eq "false") {
          $zipTarget = -join("denise_", $env:Target, "_build_", $env:APPVEYOR_REPO_COMMIT.Substring(0, 7), ".zip");
          $zipSrc = -join("denise_", $env:Target, "_build_", $env:APPVEYOR_REPO_COMMIT.Substring(0, 7));
          
        } else {
          $zipTarget = -join("denise_", $env:Target, "_", $env:APPVEYOR_REPO_TAG_NAME, ".zip");
          $zipSrc = -join("denise_", $env:Target, "_", $env:APPVEYOR_REPO_TAG_NAME);                  
        }
        ren out $zipSrc; Compress-Archive -Path $zipSrc -DestinationPath $zipTarget 

  deploy_script:
    - ps: |
        if($env:APPVEYOR_REPO_TAG -eq "true") {
          $zipTarget = -join("denise_", $env:Target, "_", $env:APPVEYOR_REPO_TAG_NAME, ".zip");
          choco install --no-progress -y winscp
          echo 'open sftp://piciji:%FTP_PSW%@frs.sourceforge.net/ -hostkey="acceptnew"' > ftp.txt 2>&1
          -join("put ", $zipTarget,' "/home/frs/project/deniseemu/v 2.2.1/"') >> ftp.txt
          echo exit >> ftp.txt
          $env:Path += 'C:\Program Files (x86)\WinSCP;'
          winscp.com /script=ftp.txt
          del ftp.txt
        }

  artifacts:
    - path: 'denise*.zip'
   
-
  matrix:
    only:
      - image: Ubuntu2004
      
  install:
    - sh: sudo apt-get --allow-releaseinfo-change update
    - sh: sudo apt-get install mesa-common-dev -y
    - sh: sudo apt-get install libgtk-3-dev -y
    - sh: sudo apt-get install libopenal-dev -y
    - sh: sudo apt-get install libpulse-dev -y
    - sh: sudo apt-get install libsdl2-dev -y
    - sh: sudo apt-get install libudev-dev -y
    - sh: sudo apt-get install sshpass -y
    
  build_script:
    - sh: make
  
  after_build:
    - sh: sudo rm out/.gitkeep
    - sh: sudo mkdir -p out/translation
    - sh: sudo mkdir -p out/data
    - sh: sudo mkdir -p out/fonts
    - sh: sudo mkdir -p out/shader
    - sh: sudo mkdir -p out/img
    - sh: sudo mkdir -p out/sounds
    - sh: sudo cp data/img/denise.png out/
    - sh: sudo cp data/denise.desktop out/
    - sh: sudo cp data/application-x-denise.xml out/
    - sh: sudo cp data/translation/* out/translation/
    - sh: sudo cp data/data/* out/data/
    - sh: sudo cp data/fonts/*.ttf out/fonts/
    - sh: sudo cp data/img/bundle/* out/img/
    - sh: sudo cp -r data/sounds/* out/sounds/
    - sh: sudo cp -r data/shader/* out/shader/
    - sh: sudo cp data/install.sh out/
    - sh: sudo cp data/uninstall.sh out/
    - sh: sudo cp data/txt/licence.md out/
    - sh: sudo cp readme.md out/
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "false" ]
        then
          export gzTarget=denise_ubuntu2004_build_$(echo ${APPVEYOR_REPO_COMMIT} | cut -c 1-7).tar.gz
          export gzSrc=denise_ubuntu2004_build_$(echo ${APPVEYOR_REPO_COMMIT} | cut -c 1-7)
          
        else        
          export gzTarget=denise_ubuntu2004_${APPVEYOR_REPO_TAG_NAME}.tar.gz
          export gzSrc=denise_ubuntu2004_${APPVEYOR_REPO_TAG_NAME}
        fi
        
        sudo mv out "${gzSrc}" && sudo tar -zcf "${gzTarget}" "${gzSrc}"    

  deploy_script:
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "true" ]
        then
          export gzTarget=denise_ubuntu2004_${APPVEYOR_REPO_TAG_NAME}.tar.gz
          echo ${FTP_PSW} > ftp.txt 2>&1
          sshpass -f "ftp.txt" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${gzTarget}" piciji@frs.sourceforge.net:"/home/frs/project/deniseemu/v\\ 2.2.1/"
        fi

  artifacts:
    - path: 'denise*.tar.gz'  
    
-  
  matrix:
    only:
      - image: macos
      
  install:      
    - sh: test -e freetype-2.13.0.tar.gz && echo "File exists" || curl -L https://download.savannah.gnu.org/releases/freetype/freetype-2.13.0.tar.gz --output freetype-2.13.0.tar.gz
    - tar -zxf freetype-2.13.0.tar.gz
    - sh: sudo pip install dmgbuild
    - sh: test -e sshpass-1.08.tar.gz && echo "File exists" || curl -L https://onboardcloud.dl.sourceforge.net/project/sshpass/sshpass/1.08/sshpass-1.08.tar.gz --output sshpass-1.08.tar.gz
    - tar -zxf sshpass-1.08.tar.gz
    
  cache:
    - freetype-2.13.0.tar.gz
    - sshpass-1.08.tar.gz
    
  before_build:
    - sh: export MACOSX_DEPLOYMENT_TARGET=10.9
    
  build_script:
    - sh: cd freetype-2.13.0
    - sh: ./configure --enable-static --without-zlib --without-bzip2 --without-png && make && make install
    - sh: cd ..  
    - sh: cd sshpass*
    - sh: ./configure && make install
    - sh: cd ..
    - sh: make && make install
    
  after_build:
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "false" ]
        then
          export gzTarget=denise_osx_build_$(echo ${APPVEYOR_REPO_COMMIT} | cut -c 1-7).dmg
          export gzSrc=out/Denise.dmg
          
        else        
          export gzTarget=denise_osx_${APPVEYOR_REPO_TAG_NAME}.dmg
          export gzSrc=out/Denise.dmg
        fi
        
        sudo mv "${gzSrc}" "${gzTarget}"

  deploy_script:
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "true" ]
        then
          export gzTarget=denise_osx_${APPVEYOR_REPO_TAG_NAME}.dmg
          echo ${FTP_PSW} > ftp.txt 2>&1
          sshpass -f "ftp.txt" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${gzTarget}" piciji@frs.sourceforge.net:"/home/frs/project/deniseemu/v\\ 2.2.1/"
        fi

  artifacts:
    - path: 'denise*.dmg'

-
  matrix:
    only:
      - image: macos-bigsur

  install:
    - sh: test -e freetype-2.13.0.tar.gz && echo "File exists" || curl -L https://download.savannah.gnu.org/releases/freetype/freetype-2.13.0.tar.gz --output freetype-2.13.0.tar.gz
    - tar -zxf freetype-2.13.0.tar.gz
    - sh: sudo pip install dmgbuild
    - sh: test -e sshpass-1.08.tar.gz && echo "File exists" || curl -L https://onboardcloud.dl.sourceforge.net/project/sshpass/sshpass/1.08/sshpass-1.08.tar.gz --output sshpass-1.08.tar.gz
    - tar -zxf sshpass-1.08.tar.gz

  cache:
    - freetype-2.13.0.tar.gz
    - sshpass-1.08.tar.gz

  before_build:
    - sh: export MACOSX_DEPLOYMENT_TARGET=11

  build_script:
    - sh: cd freetype-2.13.0
    - sh: ./configure --host=arm64-apple-macos11 --enable-static --without-zlib --without-bzip2 --without-png && make && make install
    - sh: cd ..
    - sh: install -m 755 data/libs/static/macArm/libfreetype.a /usr/local/lib/
    - sh: install -m 755 data/libs/shared/macArm/libfreetype.6.dylib /usr/local/lib/
    - sh: cd sshpass*
    - sh: ./configure && make install
    - sh: cd ..
    - sh: make Arch=arm64-apple-macos11 && make install

  after_build:
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "false" ]
        then
          export gzTarget=denise_osx_arm64_build_$(echo ${APPVEYOR_REPO_COMMIT} | cut -c 1-7).dmg
          export gzSrc=out/Denise.dmg
        
        else        
          export gzTarget=denise_osx_arm64_${APPVEYOR_REPO_TAG_NAME}.dmg
          export gzSrc=out/Denise.dmg
        fi
        
        sudo mv "${gzSrc}" "${gzTarget}"

  deploy_script:
    - sh: |
        if [ "${APPVEYOR_REPO_TAG}" == "true" ]
        then
          export gzTarget=denise_osx_arm64_${APPVEYOR_REPO_TAG_NAME}.dmg
          echo ${FTP_PSW} > ftp.txt 2>&1        
          sshpass -f "ftp.txt" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${gzTarget}" piciji@frs.sourceforge.net:"/home/frs/project/deniseemu/v\\ 2.2.1/"
        fi

  artifacts:
    - path: 'denise*.dmg'

