
#pragma once

#include "../cart/freezeButton.h"

namespace LIBC64 {

/*
 * Trilogic Expert Cartridge
 *
 * The cartridge has no ROM.  A CRT CHIP packet contains the initial image of
 * its 8 KiB RAM; after attach, expertRam is the only live storage.
 *
 * The real /GAME signal is generated by address-dependent logic.  clock()
 * therefore updates the expansion-port memory mode from the current CPU
 * address bus instead of keeping Denise in a static Ultimax PLA mode.
 */
struct Expert : FreezeButton {

    static constexpr unsigned RamSize = 8 * 1024;

    enum class SwitchMode : uint8_t {
        Off,
        Prg,
        On
    };

    Expert(System* system) : FreezeButton(system, true, true) {
        setId(Interface::ExpansionIdExpert);
    }

    uint8_t expertRam[RamSize] = {};
    SwitchMode switchMode = SwitchMode::Off;
    bool ramEnabled = false;
    bool ramWriteable = false;
    bool ioRegisterEnabled = false;
    bool imageValid = false;
    bool nmiObserved = false;
    bool switchOn = false;
    bool switchPrg = false;

    auto create(Interface::CartridgeId cartridgeId, unsigned size) -> Cart* override;

    auto assign(Cart* cart) -> void override;

    auto setRom(Emulator::Interface::Media* media, uint8_t* rom, unsigned romSize) -> void override;

    auto readChips() -> bool override;

    auto assumeChips() -> void override;

    auto prepare() -> void;

    auto isBootable() -> bool override {
        return false;
    }

    auto blockFreeze() -> bool override {
        return !imageValid || switchMode != SwitchMode::On;
    }

    auto hasCustomButton() -> bool override {
        return true;
    }

    auto customButton() -> void override {
        system->power(true);
    }

    auto switchToUltimax() -> bool override {
        /* Expert's /GAME is address decoded, not a static Ultimax signal. */
        return false;
    }

    auto setSwitchMode(SwitchMode mode) -> void;

    auto setJumper(unsigned jumperId, bool state) -> void override;

    auto getJumper(unsigned jumperId) -> bool override;

    auto reset(bool softReset = false) -> void override;

    auto clock() -> void override;

    auto didFreeze() -> void override;

    auto observeNmi(bool state) -> void override;

    auto readIo1(uint16_t addr) -> uint8_t override {
        io1Access();
        /* The Expert register never drives valid data onto the bus. */
        return ExpansionPort::readIo1(addr);
    }

    auto peekIo1(uint16_t addr) -> uint8_t override {
        return ExpansionPort::peekIo1(addr);
    }

    auto writeIo1(uint16_t addr, uint8_t value) -> void override {
        (void)addr;
        (void)value;
        io1Access();
    }

    auto readRomL(uint16_t addr) -> uint8_t override {
        return expertRam[addr & 0x1fff];
    }

    auto peekRomL(uint16_t addr) -> uint8_t override {
        return expertRam[addr & 0x1fff];
    }

    auto readRomH(uint16_t addr) -> uint8_t override {
        return expertRam[addr & 0x1fff];
    }

    auto peekRomH(uint16_t addr) -> uint8_t override {
        return expertRam[addr & 0x1fff];
    }

    auto writeRomL(uint16_t addr, uint8_t value) -> void override {
        if (ramEnabled && ramWriteable)
            expertRam[addr & 0x1fff] = value;
    }

    auto writeUltimaxRomL(uint16_t addr, uint8_t value) -> void override {
        writeRomL(addr, value);
    }

    auto writeRomH(uint16_t addr, uint8_t value) -> void override {
        (void)addr;
        (void)value;
    }

    auto writeUltimaxRomH(uint16_t addr, uint8_t value) -> void override {
        (void)addr;
        (void)value;
    }

    auto serialize(Emulator::Serializer& s) -> void override;

private:
    auto enableOnMode() -> void;

    auto disableRam() -> void;

    auto io1Access() -> void;
};

} // namespace LIBC64
