
#pragma once

#include "controlPort.h"
#include "../../vicII/vicII.h"
#include "../input.h"
#include "../../../tools/crop.h"

#define CURSOR_PEN_WIDTH 7
#define CURSOR_GUN_WIDTH 13

namespace LIBC64 {
    
struct LightControl : ControlPort {
    
    int16_t posX;
    int16_t posY;
    // offsets generated by the device
    int xOffset = 0;
    int yOffset = 0;
    
    int cy = 0;
    
    struct Cursor {
        bool center;
        unsigned size;
        const uint8_t* data;
    };
    
    uint8_t cyclePixel = 0;
    uint8_t* displayPtr = nullptr;
    
    bool button1Pressed = false;
    bool button2Pressed = false;    

    Emulator::Crop<uint8_t>::Latest* cropLatest = nullptr;
    
    // it's exactly what you think :-)
    // we need a cursor to track movement. (aiming with the gun)
    // we draw the cursor in emulated frame, before we send it to host.
    const uint8_t cursorGun[CURSOR_GUN_WIDTH * CURSOR_GUN_WIDTH] = {
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        2,2,2,2,2,2,0,2,2,2,2,2,2,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
        0,0,0,0,0,0,2,0,0,0,0,0,0,
    };
    /*
    const uint8_t cursorGun[CURSOR_GUN_WIDTH * CURSOR_GUN_WIDTH] = {
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        1,1,1,1,1,1,2,1,1,1,1,1,1,
        2,2,2,2,2,2,0,2,2,2,2,2,2,
        1,1,1,1,1,1,2,1,1,1,1,1,1,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
        0,0,0,0,0,1,2,1,0,0,0,0,0,
    };
    */
    inline auto getCursorGunWidth() -> unsigned {
        
        return CURSOR_GUN_WIDTH;
    }

    const uint8_t cursorPen[CURSOR_PEN_WIDTH * CURSOR_PEN_WIDTH] = {
        0,0,0,0,0,0,2,
        0,0,0,0,0,2,0,
        0,0,0,0,2,0,0,
        0,0,0,2,0,0,0,
        0,0,2,0,0,0,0,
        0,2,0,0,0,0,0,
        1,0,0,0,0,0,0,
    };   
    
    inline auto getCursorPenWidth() -> unsigned {
        
        return CURSOR_PEN_WIDTH;
    }    
    
    virtual auto getCursorData() -> Cursor = 0;
    
    std::function<void ()> triggerOn;
    std::function<void ()> triggerOff;
    
    LightControl( System* system, Interface::Device* device ) : ControlPort( system, device ) { }
    
    virtual auto setTrigger() -> void {
                
        triggerOn = [this]() {

            // control port 2 can not access the Vic light input
            if ( this == system->input.controlPort2 )
                return;
            
            vicII->triggerLightPen( 0, cyclePixel >> 1 );            

            // i don't know how much cycles the gun/pen device is holding the fire pin low, a cycle would
            // be enough for the Vic to recognize.
            // lpx and lpy will be latched one time per frame only. From a Vic point of view it doesn't matter 
            // how much cycles the fire pin will be held low, at least if it resets before frame is completed.
            // from a Cia point of view it matters. the control port 1 fire pin can trigger the Vic, doesn't matter
            // if the Cia forces the pin to output.
            // the cia could read the light trigger on fire pin. of course the programmer doesn't know when this 
            // happens. so it would be quite useless and more useless if the trigger lasts only one cycle.

            sysTimer.add( &triggerOff, 1 );            
        };
        
        triggerOff = [this]() {
            
            vicII->triggerLightPen( 1 );
        };
    }
    
    auto read( ) -> uint8_t { 
        
        uint8_t out = 0xff;
        
        // trigger pin is active
        if ( sysTimer.has( &triggerOff ) )                        
            out &= ~(1 << 4);
        
        return out;        
    }

    auto draw( uint16_t color ) -> void {
        
        if (device->userData & 1) {
            if (!system->warp.config)
                device->userData &= ~1; 
            
            return;
        }
		
		if(!cropLatest->frame)
			return;
        
        int vx, vx1;
        int vy, vy1;          
        
        unsigned lineWidth = cropLatest->width + cropLatest->linePitch;
        unsigned cursorHalfSize = 0;
        Cursor cursor = getCursorData();       

        if ( cursor.center ) {
            cursorHalfSize = cursor.size / 2;
            vy = posY - cursorHalfSize;
        } else
            vy = posY - (cursor.size - 1);   
        
        vx = posX - cursorHalfSize;
        
        for (; cy < cursor.size; cy++) {

            vy1 = vy + cy;
             
            if ( vy1 <= 0 || vy1 >= cropLatest->height )
                continue;

            for (int cx = 0; cx < cursor.size; cx++) {
                
                vx1 = vx + cx;
                
                if (vx1 < 0 || vx1 >= cropLatest->width )
                    continue;
                
                uint8_t pixel = cursor.data[cy * cursor.size + cx];
                
                if (pixel == 0)
                    continue;
                
                *(cropLatest->frame + vy1 * lineWidth + vx1) = ( pixel == 1 ) ? 0 : color;                
            }            
        }
    }    
    
    virtual auto useButton1Internal() -> bool {
        
        return false;
    }
    
    auto poll( ) -> void {
        cy = 0;
        
        button1Pressed = interface->inputPoll( device->id, 2 ) & 1;
        
        if ( device->inputs.size() >= 4 )
            button2Pressed = interface->inputPoll( device->id, 3 ) & 1;
        
        if (device->userData & 1) { // get absolute mouse position
            posX = interface->inputPoll( device->id, 0);
            posY = interface->inputPoll( device->id, 1);
            
        } else {
            posX += interface->inputPoll( device->id, 0);
            posY += interface->inputPoll( device->id, 1);
        }
                
        setBoundaries();
        
        if ( isOffscreen() || ( useButton1Internal() && !button1Pressed) )
            return;        
        
        int x = posX + system->crop->left + xOffset;
        int y = posY + system->crop->top + yOffset;
        
        displayPtr = nullptr;        
        cyclePixel = 0;
        
        unsigned cycles = vicII->getCyclesForNextLightTrigger( x, y, cyclePixel );
        
        if ( cycles )
            sysTimer.add( &triggerOn, cycles );
    }
    
    auto setBoundaries( ) -> void {
        // lets force screen coordinates within (cropped) display area.
        
        posX = std::max((int16_t)-2, std::min((int16_t)(cropLatest->width + 2), posX));
        posY = std::max((int16_t)-2, std::min((int16_t)(cropLatest->height + 2), posY));
    }
    
    auto isOffscreen() -> bool {        
        
        return posY < 0 || posY >= cropLatest->height || posX < 0 || posX >= cropLatest->width;
    }
             
    virtual auto reset() -> void {
        
        sysTimer.remove( &triggerOn );
        sysTimer.remove( &triggerOff );
        button1Pressed = button2Pressed = false;
        cyclePixel = 0;
        displayPtr = nullptr;
        posX = 0;
        posY = 0;  
        cropLatest = &system->crop->latest;
        
        setTrigger();
    }
    
    auto getCursorPosition( int16_t& x, int16_t& y ) -> bool {
        
        x = posX;
        y = posY;
        
        // disable cursor rendering
        device->userData |= 1;
        
        return true;
    }
    
    virtual auto serialize(Emulator::Serializer& s) -> void {
        
        s.integer( posX );
        s.integer( posY );
        
        s.integer( xOffset );
        s.integer( yOffset );
        
        s.integer( cyclePixel );
        
        s.integer( button1Pressed );
        s.integer( button2Pressed );
    }

    auto allowJit() -> bool { return false; }
};

}
