
/**
 * 68000 emulation should be feature complete
 * 
 * 68010 emulation lacks long stack frame creation for bus/address errors
 * and therefore resuming of suspended instructions via rte instruction
 * 
 * 68020 emulation lacks long stack frame creation like 68010 and
 * coprocessors (mmu, fpu) are currently not supported
 */

#pragma once

#include "context.h"

namespace M68FAMILY {
	
struct M68Model {
	/** interrupt types */
	enum : uint8_t { USER_VECTOR/*Amiga*/, AUTO_VECTOR/*Genesis*/, SPURIOUS, UNINITIALIZED };
	/** set interrupt type, default is AUTO_VECTOR */
	virtual auto setInterruptType( uint8_t type ) -> void = 0;
	/** hard reset, includes reset exception */
	virtual auto power() -> void = 0;
	/** performs reset exception */
	virtual auto reset() -> void = 0;
	/** process next opcode */
	virtual auto process() -> void = 0;
	/** seted by external device (level 0 - 7), 0 -> DISABLE, 7 -> NMI.
	 cycle is used for 68020+, based on consumed cycles ahead of other bus masters */
	virtual auto setInterrupt( uint8_t level, unsigned cycle = 0) -> void = 0;
	/** last readed value from program counter */
	virtual auto openBus() -> uint32_t = 0;	
	/** bus error is generated by an external device (available in Atari ST, not in Amiga or Genesis),
    call it as a result of an unwanted memory access */
    virtual auto raiseBusError(uint32_t addr) -> void = 0;
	/** get cpu pins FC0 - FC2
	 can be overriden with sfc or dfc for moves instruction */
	virtual auto getFunctionCodes() -> uint8_t = 0;	
	/** 68000 cpu can do nothing while waiting for free bus.
	for 68020+ add wait states to prolong sequencer */
	virtual auto addWaitStates(unsigned cycles) -> void {}
	/** set a prepared context by defining callbacks,
	for resuming you have to set internal values too */	
	virtual auto setContext( M68Context* context ) -> void = 0;
	/** creates a new context */
	static auto createContext() -> M68Context* { return new M68Context; }
	/** creates a 68000 cpu instance */
    static auto create68000() -> M68Model*;
	/** creates a 68010 cpu instance */
    static auto create68010() -> M68Model*;
	/** creates a 68020 cpu instance */
	static auto create68020() -> M68Model*;
	
	virtual ~M68Model() = default;
};

//shortcuts
/** creates a new context */
static auto createContext() -> M68Context* {
	return M68Model::createContext();
}
/** creates a 68000 cpu instance */
static auto create68000() -> M68Model* {
	return M68Model::create68000();
}
/** creates a 68010 cpu instance */
static auto create68010() -> M68Model* {
	return M68Model::create68010();
}
/** creates a 68020 cpu instance */
static auto create68020() -> M68Model* {
	return M68Model::create68020();
}

}

typedef M68FAMILY::M68Model M68Model;
typedef M68FAMILY::M68Context M68Context;