
//  This code is a modification of the resid engine in VICE
//  You can get a copy of the original here: https://sourceforge.net/projects/vice-emu/

//  ---------------------------------------------------------------------------
//  This file is part of VICE, the Versatile Commodore Emulator.
//  This file is part of reSID, a MOS6581 SID emulator engine.
//  Copyright (C) 2010  Dag Lem <resid@nimrod.no>
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//  ---------------------------------------------------------------------------

#include "../sid.h"

#include <vector>

namespace LIBC64 {

doublePoint Sid::Filter::opamp6581[] = {
	{ 0.81, 10.31 }, // vmin, vmax
	{ 0.81, 10.31 }, // Repeated point
	{ 2.40, 10.31 },
	{ 2.60, 10.30 },
	{ 2.70, 10.29 },
	{ 2.80, 10.26 },
	{ 2.90, 10.17 },
	{ 3.00, 10.04 },
	{ 3.10, 9.83 },
	{ 3.20, 9.58 },
	{ 3.30, 9.32 },
	{ 3.50, 8.69 },
	{ 3.70, 8.00 },
	{ 4.00, 6.89 },
	{ 4.40, 5.21 },
	{ 4.54, 4.54 }, // Working point (vi = vo)
	{ 4.60, 4.19 },
	{ 4.80, 3.00 },
	{ 4.90, 2.30 }, // Change of curvature
	{ 4.95, 2.03 },
	{ 5.00, 1.88 },
	{ 5.05, 1.77 },
	{ 5.10, 1.69 },
	{ 5.20, 1.58 },
	{ 5.40, 1.44 },
	{ 5.60, 1.33 },
	{ 5.80, 1.26 },
	{ 6.00, 1.21 },
	{ 6.40, 1.12 },
	{ 7.00, 1.02 },
	{ 7.50, 0.97 },
	{ 8.50, 0.89 },
	{ 10.00, 0.81 },
	{ 10.31, 0.81 }, // Approximate end of actual range
	{ 10.31, 0.81 } // Repeated end point
};

doublePoint Sid::Filter::opamp8580[] = {
	{ 1.30, 8.91 }, // vmin, vmax
	{ 1.30, 8.91 }, // Repeated end point
	{ 4.76, 8.91 },
	{ 4.77, 8.90 },
	{ 4.78, 8.88 },
	{ 4.785, 8.86 },
	{ 4.79, 8.80 },
	{ 4.795, 8.60 },
	{ 4.80, 8.25 },
	{ 4.805, 7.50 },
	{ 4.81, 6.10 },
	{ 4.815, 4.05 }, // Change of curvature
	{ 4.82, 2.27 },
	{ 4.825, 1.65 },
	{ 4.83, 1.55 },
	{ 4.84, 1.47 },
	{ 4.85, 1.43 },
	{ 4.87, 1.37 },
	{ 4.90, 1.34 },
	{ 5.00, 1.30 },
	{ 5.10, 1.30 },
	{ 8.91, 1.30 }, // Approximate end of actual range
	{ 8.91, 1.30 } // Repeated end point
};

Sid::Filter::Parameter Sid::Filter::parameter[2] = {
	{
		opamp6581,
		sizeof (opamp6581 ) / sizeof (*opamp6581 ),
		// The dynamic analog range of one voice is approximately 1.5V,
		1.5,
		// riding at a DC level of approximately 5.0V.
		5.0,
		// Capacitor value.
		470e-12,
		// Transistor parameters.
		12.18,
		1.31,
		26.0e-3,
		1.0,
		20e-6,
		9.0 / 1.0,
		1.0 / 115,
		// DAC parameters.
		6.65,
		2.63,
		2.20,
		false
	},
	{
		opamp8580,
		sizeof (opamp8580 ) / sizeof (*opamp8580 ),
		// FIXME: Measure for the 8580.
		0.2,
		// The 4.75V voltage for the virtual ground is generated by a PolySi resistor divider
		4.80,
		// Capacitor value.
		22e-9,
		// Transistor parameters.
		9.09,
		0.80,
		26.0e-3,
		1.0,
		100e-6,
		// FIXME: 6581 only
		0,
		0,
		0,
		0,
		2.00,
		true
	}
};

Sid::Filter::Calculated Sid::Filter::calculated[2] = { {0}, {0} };

unsigned short Sid::Filter::resonance[16][1 << 16];
unsigned short Sid::Filter::vcr_kVg[1 << 16];
unsigned short Sid::Filter::vcr_n_Ids_term[1 << 16];

int Sid::Filter::n_snake = 0;

Sid::Filter::Filter( Sid* sid ) {
    this->sid = sid;
	static bool initialized = false;
    digiBoost = false;

	if ( !initialized )
		build( ); // one time only, doesn't matter of instance count

    v1P = &v1;
    v2P = &v2;
    v3P = &v3;
    veP = &ve;
    VhpP = &Vhp;
    VlpP = &Vlp;
    VbpP = &Vbp;
    VbpResP = &VbpRes;
    
	initialized = true;
	Vw_bias = 0; 
    setEnable( true );
    setType( MOS_6581 );
    setVoiceMask( 7 ); // 've' disabled
    adjustFilterBias6581(500);
    adjustFilterBias8580(0);
    input(0);
    reset();    
}

auto Sid::Filter::build( ) -> void {
	// Der Sid Filter ist im Rahmen der c64 Emulation am kompliziertesten.
	// An der Stelle möchte ich den Schaltkreis etwas detaillierter erklären. (Korrekturen / Verbesserungen sind gern erwünscht)
	// Warum ist der Sid Filter so kompliziert im Vergleich zur Cpu oder VicII ?
	// Zuerst müssen wir verstehen wie der Sid den Ton aus dem Chip transportiert. Dies geschieht über nur einen Pin (audio out).
	// Die permanenten Spannungswechsel definieren den Ton. Multipliziert man jede Spannung mit dem gleichen Wert verändert
	// sich nur die Lautstärke (Amplitude), da die Spannungsänderungen im gleichen Verhältnis bleiben.
	// Die Häufigkeit der Spannungsänderungen wird als Frequenz bezeichnet. Schnelle Wechsel empfinden wir als hohe Töne,
	// langsame Wechsel als tiefe Töne.
	// 'Voice' und 'Envelope' Generierung erfolgt in einem digitalen Kontext. Im Anschluss werden diese mittels
	// Digital-Analog Wandler in Spannungen überführt. Wir verlassen also die digitale Welt. Die Filter Funktionen manipulieren
	// die ausgehenden Spannungen in Abhängigkeit der Frequenz. Somit lassen sich die Amplituden hoher oder tiefer Frequenzen abschwächen.
	// Um dies zu erreichen, werden keine Register Werte eineindeutig addiert oder verschoben wie dies in anderen Chips
	// der Fall ist. Wir müssen die physikalischen Eigenschaften von Transistoren mit mathematischen Modellen beschreiben.
	// Derartige Modelle beschreiben jedoch nur idealisierte Zustände. Eine wirklich exakte Emulation ist nur annährend erreichbar.
	// Tröstlich ist, dass der original Chip selbst in jedem c64 aufgrund der damaligen Fertigungs-Fehler geringfügig anders klingt.

	unsigned int* voltages = new unsigned int[ 1 << 16 ];

	// einmalige Vorberechnungen für alle Instanzen
	for ( unsigned m = 0; m < 2; m++ ) { // m = 0 -> 6581, m = 1 -> 8580
		Parameter& pa = parameter[m];
		Calculated& ca = calculated[m];
		// Beginnen wir mit den invertierenden Operations Verstärkern (op-amps) zum Ausgleich von Signal Verlust.
		// Obige Tabellen zeigen einige Messpunkte am Original.
		// Unser erstes großes Ziel ist es, aus den vorhandenen Messpunkten auf weitere dazwischen liegende zu schlußfolgern.
		// Der erste Messpunkt beschreibt die geringste gemessene Eingangsspannung.         
		double vmin = pa.opampVoltage[0][0];
		// Durch die Invertierung ergiebt sich die dazu höchst gemessene Ausgangsspannung.
		double opampMax = pa.opampVoltage[0][1];
		// Vdd ist die Gesamtspannung welche dem Stromkreis als Gleichspannung angelegt ist. Vth (Threshold) ist die Minimal
		// Spannung, welche notwendig ist damit der Stromkreis überhaupt funktioniert. Die Effektiv Spannung ist demnach die Gesamt Spannung
		// weniger der Grenz Spannung. Diese Spannung kann der op-amp nicht überschreiten.
		// Durch den Material Faktor 'k' verringert sich die Effektiv Spannung etwas.
		double kVddt = pa.k * ( pa.Vdd - pa.Vth );
		double vmax = kVddt < opampMax ? opampMax : kVddt;
		// In diesem Spannungs Bereich arbeitet der op-amp.
		double denorm = vmax - vmin;
		// Wir normalisieren um später in verschiedene ganz zahlige Bereiche skalieren zu können.
		double norm = 1.0 / denorm;
		// Nun beleuchten wir das Thema Skalierung. Warum skalieren wir? Wie skalieren wir?
		// Spannungen werden als Gleitkommazahlen dargestellt. z.B. 3.05 Volt
		// Wir können jedoch keine Spannungen an den audio driver direkt übergeben. Dieser erwartet eine Vorzeichen behaftete
		// Ganzzahl z.B. 16 bit	(15 bit + Vorzeichen bit) -> 65535 Zustände
		// Wir übersetzen die Spannung in eine Ganzzahl. Dafür benötigen wir die Maximal Differenz "denorm" aus kleinster und größter Spannung.
		// Die Maximal Differenz entspricht dabei der größt möglichen Ganzzahl des Ziel Bereiches.
		// Im selben Verhältnis lassen sich alle Werte skalieren.
		// denorm / x = (2^n bits - 1) / y  umgestellt: y = (x * (2^n bits - 1) ) / denorm
		// oder y = x * (2^n bits - 1) * norm		
        // Lassen wir den Faktor 'x' weg, erhalten wir einen konstanten Skalierungs Faktor für jeweils einen Ziel Bereich.
		double N16 = norm * ( ( 1u << 16 ) - 1 ); // 16 bit
		ca.vo_N16 = N16;
		// Mehr bits bedeutet eine höhere Genauigkeit. Somit lassen sich immer feinere Unterschiede in den Spannungen Ganzzahlen zuordnen.
		// Je begrenzter die Genauigkeit desto eher steht die selbe Ganzzahl für verschiedene Spannungen.		
		double N30 = norm * ( ( 1u << 30 ) - 1 ); // 30 bit
		double N31 = norm * ( ( 1u << 31 ) - 1 ); // 31 bit
		double N14 = norm * ( 1u << 14 );
        // Wir können verschieden skalierete Werte mit einander multiplizieren oder dividieren. Dadurch ändert sich die Skalierung
        // des Produktes bzw des Quotienten. Die neue Skalierung erhalten wir durch Addition bzw Subtraktion der Skalierung.
        // z.B. 2^16 * 2^16 = 2^(16+16) = 2^32, 2^30 / 2^14 = 2^(30-14) = 2^16
        // Aufpassen müssen wir bei Addition bzw. Subtraktion. Hierbei müssen beide Seiten gleich skaliert sein.
        
		// Ausgangspunkt sind die voice ( 12 bit ) und dazu gehörige envelope ( 8 bit ). Envelope moduliert die amplitude der voice,
		// eine Art Lautstärke Umschlag. Die dafür notwendige Multiplikation ergibt eine maximale digitale Spanne von 20 bits für die voice
		// Eine Voice bewegt sich in einem Intervall von 1.5 V (6581). Betrag aus negativer und positiver Spannung |-V| + |V| = 1.5 V,
		// heißt die 20 bits beschreiben die Abstufungen in diesem Interval.
		// Zuerst übersetzen wir 1,5 Volt in eine Ganzzahl in unserem "denorm" Bereich. Die Ziel Bereichs Spanne ist 16 bit.
		// scale_1.5 = N16 * 1.5 V (6581)		
		// Jetzt skalieren wir die 20 bit breite voice in nur diese 1.5 Volt Spanne unseres Gesamt Bereiches hinein.
		// scale_1.5 / x = 2^20 / voice
		// x = voice * scale_1.5 / 2^20
		// x = voice * N16 * 1.5 V / 2^20
		// Leider übersteigt die Multiplikation den Wertebereich von int und c++ erwartet eine long long Konvertierung.
		// Um eine long long Konvertierung zu vermeiden, dürfen keine Zwischenergebnisse 32 bit überschreiten
		// Deswegen skalieren wir in einen kleineren Bereich: N14 reicht aus, da die voice maximal 1,5 Volt
        // umfasst. Um den Wert der Gleichung nicht zu verändern, teilen wir durch 2^18 anstatt 2^20.
		// x = voice * N14 * 1.5 V / 2^18
		// Wir bereiten den Multiplikator so weit wie möglich vor.
		ca.voiceScaleS14 = (int) ( N14 * pa.voiceVoltageRange );
        if (m == 1)
            ca.voiceScaleS14Old = (int) ( N14 * 1.0 );
		// Neben dem Multiplikator um eine beliebige voice in unseren Ziel Bereich zu skalieren, benötigen wir noch den
		// Nullpunkt zu welchem die voice auf addiert wird.
		// Die voice ist vorzeichenbehaftet und wird den Nullpunkt unterschreiten bzw. überschreiten.
		// Natürlich muss auch die Nullpunkt Spannung in unseren 16 bit breiten Ganzzahl Bereich skaliert werden.
        // Davor ist jedoch noch ein weiterer Schritt zu erledigen. Der Bereich in den skaliert wird, betrachtet 'vmin'
        // als kleinst möglichen Wert anstatt 0 Volt. Verwenden wir am Chip gemessene Spannungen müssen diese erst in den
        // Bereich vmin <-> vmax vor der Skalierung übersetzt werden. Dies geschieht einfach durch Abzug von 'vmin'.
		ca.voiceDC = (int) ( N16 * ( pa.voiceDCVoltage - vmin ) );
        if (m == 1)
            ca.voiceDCOld = (int) ( N16 * ( 1.30 - vmin ) );
		
		// Wir benötigen noch eine skalierte Ganzahl für die Effektivspannung.
		// + 0.5 bewirkt das immer aufgerundet wird, anstatt erst ab 0.5: also 6.1 + 0.5 = 6.6 = 7; 6.8 + 0.5 = 7.3 = 7
		ca.kVddt = (int) ( N16 * ( kVddt - vmin ) + 0.5 );
        // Zudem skalieren wir kVddt getrennt von vmin 
		ca.kVddtWithoutVmin = N16 * kVddt;
		ca.vmin = N16 * vmin;
        // Alle Laufzeit Berechnungen sollen ausschließlich auf die struct 'Calculated' zugreifen.
        ca.k = pa.k;
		
		// Obige Messpunkte für Ein- und Ausgangsspannung der op-amps sind zwar schon sehr ausführlich aber skaliert in einen 16 bit
		// Ganzzahl Bereich fehlen doch etliche Zwischenwerte. Wir ergänzen die fehlenden Punkte durch Interpolation.
		// Ziel ist es einen harmonischen Kurvenverlauf durch die bestehenden Punkte zu führen und somit die fehlenden 
		// zu ermitteln. Zuerst benötigen wir ein mapping für X und Y im Koordinatensystem: vo - vx -> vx
		// X-Achse: delta der Spannungen vor und nach der Verstärkung
		// Y-Achse: Spannung vor der Operationsverstärkung

		std::vector<Emulator::Coordinate> scaledVoltage;
		// Für alle Messpunkte generieren wir Koordinaten.
		for ( int i = 0; i < pa.opampVoltageSize; i++ ) {
			Emulator::Coordinate coordinate;
			// X-Achse:
			// Zuerst wird das Spannungs delta jedes einzelnen Messpunktes ermittelt, dann wird skaliert.
			// 'vmin' müssen wir nicht abziehen, da es sich weg kürzt: (Vout - vmin) - (Vin - vmin)
			// Wir wollen 'x' als offset in einem Feld verwenden. Das geht natürlich nur wenn alle Werte
			// positiv sind. Dazu ordnen wir die negativen in der ersten Hälfte unseres 16 bit Wertebereiches
			// an und die positiven in der zweiten Hälfte. 
			// x + (1 << 16) / 2
			// Verwenden wir 'x' später in Formeln dürfen wir nicht vergessen zurück zu übersetzen.
			
			coordinate.x = int( N16 * ( pa.opampVoltage[i][1] - pa.opampVoltage[i][0] + denorm ) / 2 + 0.5 );
			// Y-Achse: wir skalieren die Eingangsspannung für mehr Genauigkeit auf eine größere Anzahl bits.
			coordinate.y = N31 * ( pa.opampVoltage[i][0] - vmin );
			// für aufsteigende X-Werte invertieren wir die Reihenfolge der Koordinaten
			scaledVoltage.insert( scaledVoltage.begin( ), coordinate );
		}

		// Durch Aufrundung kann der Wertebereich überschritten werden, somit muss auf den letzten Wert abgeschnitten werden.
		if ( scaledVoltage[ scaledVoltage.size( ) - 1].x >= ( 1 << 16 ) ) {
			scaledVoltage[ scaledVoltage.size( ) - 1].x =
                // Das trifft dann natürlich auch auf die vorletzte Koordinate zu, da die Werte hier wiederholt werden, siehe obige Tabellen.
				scaledVoltage[ scaledVoltage.size( ) - 2].x = ( 1 << 16 ) - 1;
		}

		// Die Interpolation ist in splines.h detailiert erklärt, inkl. sämtlicher Herleitungen
		// Die durch die Interpolation ermittelten Werte sind Ganzahlen, welchen Spannungen als Gleitkommazahlen zugewiesen sind.
		// In X-Richtung gehen wir somit in "einser" Schritten, siehe 1.0 als Schrittgröße für die 'interpolate' Funktion.
		// 'pointPlotter' wird der Datentyp übergeben in welchem die errechneten y Werte abgelegt werden sollen.
		Emulator::CatmullSpline::interpolate( scaledVoltage, Emulator::PointPlotter<unsigned int>( voltages ), 1.0 );

		ca.ak = scaledVoltage[0].x; // Minimum
		ca.bk = scaledVoltage[scaledVoltage.size( ) - 1].x; // Maximum
		
		// Das benötigen wir für die Verwendung von Newtown Raphson zur Laufzeit.
		// Wir merken uns den letzten Wert als Ausgangspunkt für die Suche des Nächsten.
		// Es ist davon auszugehen, das der nächste Wert in der Nähe des letzten liegt.
		ca.nrXFilter = (ca.ak + ca.bk) >> 1;
		ca.nrXMixer = (ca.ak + ca.bk) >> 1;

		// Initialisierung		
		for ( unsigned x = 0; x < ( 1 << 16 ); x++ ) {
			// Spannung 'vx' vor der Verstärkung
			ca.opamp[x].vx = 0;
			// Differenz direkt aufeinander folgender Spannungen 'vx'
			ca.opamp[x].dvx = 0;
		}
		// voltages erhält das Ergebnis der Interpolation
		unsigned int f = voltages[ ca.ak ]; //erster Wert
		// nur für diesen Bereich haben wir Werte im Rahmen der Interpolation errechnet
		for ( unsigned x = ca.ak; x <= ca.bk; x++ ) {
			// letzten Wert merken			
			unsigned int fp = f;
			// nächster Wert			
			f = voltages[x];
			// Wir benötigen das delta zwischen aufeinander folgenden Y-Werten. Der Grund dafür ergiebt sich im späteren Verlauf.
            // Für möglichst genaue deltas haben wir im Vorfeld Y auf 31 bit skaliert.
			// skaliert : (m * 2^31 * dy) / (m * 2^16 * dx) = 2^15 * dy/dx
			// 15 bits + Vorzeichen Bit
			int df = f - fp;
			// Die Werte der Y-Achse werden zurück auf vorzeichenlose 16 bit skaliert (31 - 15)		
			ca.opamp[x].vx = f > ( 0xffff << 15 ) ? 0xffff : f >> 15;
			// Um 'long long' Konvertierungen bei der Weiterverwendung zu vermeiden, skalieren wir etwas runter 
			// skaliert : 2^11
			ca.opamp[x].dvx = df >> ( 15 - 11 );
		}
		// Es fehlt das delta für den Start Wert, wir übernehmen den des Folgenden. ... nicht schön aber selten
		ca.opamp[ ca.ak ].dvx = ca.opamp[ ca.ak + 1 ].dvx;

        // An der Stelle erhalten wir, neben obigen Messpunkten, Werte für beliebige Spannungen am op-amp
		// und sind nun in der Lage Spannungsverläufe der Impedanzwandler vor zuberechnen.
		// Impedanzwandler werden in der Datei 'opamp.cpp' erklärt.
		// Alle Impedanzwandler im Schaltkreis haben einen Vorwiderstand R1 und einen prallel zum 
		// Operationsverstärker geschaltenen Widerstand R2.
		// Wir nutzen die Tatsache aus, das bei einer Parallelschaltung an allen Verbrauchern
		// die gleiche Spannung anliegt. Somit liegt auch am Widerstand R2 die Spannung des op-amp an.		
		// 'vx' ist die Spannung vor der Verstärkung in Spalte 1 der obigen Tabellen
		// 'vo' ist die Ausgangs Spannung nach der Verstärkung in Spalte 2
		// 'vi' ist die Eingangs Spannung an R1
		// die Schwierigkeit ist jetzt anhand der Eingangsspannung 'vi' auf die richtige unserer vorberechneten
		// Ausgangsspannungen 'vo' zu schlußfolgern, siehe Funktion 'solveOpamp'

		// [ Impedanzwandler: Lautstärke und Resonanz ]
		// Lautstärke und bandpass Resonanz sind mathematisch identisch. Beide werden durch 4 bits (16 Zustände)
		// gesteuert und die zuschaltbaren Vor Widerstände sind: 8*R (bit 0), 4*R (bit 1), 2*R (bit 2), 1*R (bit 3)
		// 'R' entspricht dabei dem  Widerstand um den Operations Verstärker.
		// Im Gesamtschaltkreis, siehe Datei 'circuit', schauen wir uns dazu den op-amp [A> direkt vor
		// 'Audio out' an.
		for ( int n8 = 0; n8 < 16; n8++ ) {
			// Die Funktion 'solveOpamp' erwartet für 'n' das Verhältnis der Geometrie
			// des Gesamt Widerstandes R1 (aller zuschaltbaren) und des Widerstandes R2 um den Verstärker.
            // In der Funktion 'solveOpamp' ist hergeleitet, das wir für 'n' = R2 / R1
            // schreiben können. Der eigentliche Widerstandswert kürzt sich raus, da es sich
            // um Vielfache handelt. R2 ergibt dabei den Faktor 1. 
			// Wenn nur bit 0 (n8 == 1) gesetzt ist, ist das Verhältnis 1/8
            // Wenn nur bit 1 (n8 == 2) gesetzt ist, ist das Verhältnis 1/4 = 2/8
            // Wenn nur bit 2 (n8 == 4) gesetzt ist, ist das Verhältnis 1/2 = 4/8
			// Wenn nur bit 3 (n8 == 8) gesetzt ist, sind beide Widerstände identisch 8/8, also n = 1
            // sind mehrere 'R1' parallel geschalten, gilt die Formel für parallele
            // Widerstände: 1 / Rges = 1 / Rx + 1 / Ry + 1 / Rz ...
            // sind z.B. bit 0 und bit 1 (n8 = 3) gesetzt: 1 / R1 = 1 / 8 + 1 / 4
            // 1 / R1 = 3 / 8
            // R1 = 8 / 3
            // R2 / R1 = 1 / (8 / 3) = 3 / 8
			// die Schrittweite beträgt demnach volume / 8 bzw. resonanz / 8			
			// Die Skalierung beträgt 2^3 = 8 ( n = 1 )
			// die Funktion 'solveOpamp' erwartet eine Skalierung von 2^7 für 'n'
			// Somit muss um 4 bit hoch skaliert werden. 2^3 * 2^4 = 2^(3+4)
            // Probe: n8 = 1 enspricht 1 << 4 = 16 / 2⁷ = 1 / 8
			int n = n8 << 4; // skaliert : 2^7            
			// kleinster Startwert für Newton-Raphson Verfahren, siehe 'solveOpamp'
			int x = ca.ak;
			// Wir ermitteln für jedes 'vi' das zugehörige 'vo' in Abhängigkeit von 'vx'
			// Das ergibt 16 * 65536 Möglichkeiten.
			for ( int vi = 0; vi < ( 1 << 16 ); vi++ ) {
				ca.gain[n8][vi] = solveOpamp( ca.opamp, n, vi, x, ca );
			}
		}
        
        // Resonanz für den 6581 ist mathematisch identisch. Schauen wir uns den Schaltkreis
        // aber genauer an sehen wir das bei der Resonanz im Gegensatz zur Lautstärke die
        // gesetzten bits eine Stromfluss Unterbrechung bedeuten, siehe Resonanz -> 1 = open und
        // Lautstärke -> 0 = open.
        // Wir invertieren dazu einfach die Register bits für Resonanz und können diese dann
        // im gleichen mathematischen Modell verwenden.
        
        // Laut Schaltkreis für den 8580 weicht die Resonanz Schaltung vom 6581 ab.
        // Zum einem sind die Widerstände von bit Kombinationen abhängig anstatt Einzel bits
        // zum anderen sind mehrere Widerstände parallel zum Verstärker geschalten und ebenso
        // von bit Kombinationen abhängig. Wir werden etwas mehr Aufwand betreiben müssen um
        // das Verhältnis 'n' zu ermitteln. Im Schaltkreis des 8580 ist dargestellt,
		// welche bits welche Widerstände zuschalten. 'Rf' ist immer aktiv.		
		// Der Gesamt Widerstand von genau 2 parallel geschaltenen Einzelwiderständen berechnet sich:     
        // Rges = (Rx * Ry) / (Rx + Ry)
        // Im Folgenden berechnen wir für alle 16 Kombinationen der 4 Resonanz bits 'n'.
        // n = Gesamt Widerstand parallel zum Verstärker / Widerstand davor
        // Der Vor Widerstand kann immer nur genau einer der 4 sein, siehe bits D6 u. D7.
		
		// Ri = 1.0
		// R1 = 15.3*Ri
		// R2 =  7.3*Ri
		// R3 =  4.7*Ri
		// Rf =  1.4*Ri
		// R4 =  1.4*Ri
		// R8 =  2.0*Ri
		// RC =  2.8*Ri
				 
        int resGain[16] ={
            (int) ((1 << 7)*(1.4 / 1.0)), //      Rf/Ri   1.4
            (int) ((1 << 7)*(((1.4 * 15.3) / (1.4 + 15.3)) / 1.0)), // (Rf|R1)/Ri   1.28263
            (int) ((1 << 7)*(((1.4 * 7.3) / (1.4 + 7.3)) / 1.0)), // (Rf|R2)/Ri   1.17471
            (int) ((1 << 7)*(((1.4 * 4.7) / (1.4 + 4.7)) / 1.0)), // (Rf|R3)/Ri   1.07869
            (int) ((1 << 7)*(1.4 / 1.4)), //      Rf/R4   1.0
            (int) ((1 << 7)*(((1.4 * 15.3) / (1.4 + 15.3)) / 1.4)), // (Rf|R1)/R4   0.916168
            (int) ((1 << 7)*(((1.4 * 7.3) / (1.4 + 7.3)) / 1.4)), // (Rf|R2)/R4   0.83908
            (int) ((1 << 7)*(((1.4 * 4.7) / (1.4 + 4.7)) / 1.4)), // (Rf|R3)/R4   0.770492
            (int) ((1 << 7)*(1.4 / 2.0)), //      Rf/R8   0.7
            (int) ((1 << 7)*(((1.4 * 15.3) / (1.4 + 15.3)) / 2.0)), // (Rf|R1)/R8   0.641317
            (int) ((1 << 7)*(((1.4 * 7.3) / (1.4 + 7.3)) / 2.0)), // (Rf|R2)/R8   0.587356
            (int) ((1 << 7)*(((1.4 * 4.7) / (1.4 + 4.7)) / 2.0)), // (Rf|R3)/R8   0.539344
            (int) ((1 << 7)*(1.4 / 2.8)), //      Rf/RC   0.5
            (int) ((1 << 7)*(((1.4 * 15.3) / (1.4 + 15.3)) / 2.8)), // (Rf|R1)/RC   0.458084
            (int) ((1 << 7)*(((1.4 * 7.3) / (1.4 + 7.3)) / 2.8)), // (Rf|R2)/RC   0.41954
            (int) ((1 << 7)*(((1.4 * 4.7) / (1.4 + 4.7)) / 2.8)), // (Rf|R3)/RC   0.385246
        };

        if (m == 1) // 8580
            // selbe Logik wie zuvor
            for (int n8 = 0; n8 < 16; n8++) {
                int x = ca.ak;
                for (int vi = 0; vi < (1 << 16); vi++) {
                    resonance[n8][vi] = solveOpamp(ca.opamp, resGain[n8], vi, x, ca);
                }
            }

		// [ Impedanzwandler: hoch pass ]
		// Als nächstes berechnen wir den hoch pass Filter Operations Verstärker.
		// Im Schaltkreis lokalisieren wir diesen. (mitte links, die vielen untereinander
		// stehenden 'R8' Widerstände)
		// tief pass und band pass Eingänge sind immer zugeschalten ( die beiden obersten 'R8')
		// die 3 voices + externe voice sind zuschaltbar.
        // Problem ist hier, das es mehr als einen Spannungs Eingang gibt.
        // Unsere Berechnungsformel, siehe 'solveOpamp', ist nur für einen Eingang
        // ausgelegt. Das Widerstandsverhältnis 'n' ergiebt für einen Eingang:
        // R8 / R8 = 1
        // Richtigerweise müsste jeder Transistor für sich berechnet werden, da
        // diese sich nicht exakt linear verhalten.
        // Jedoch wird es dann problematisch die Werte vorzuberechnen. Nehmen wir        
        // an alle 6 Eingänge sind aktiv. Jeder Eingang weist eine individuelle
        // Spannung auf. Das ergibt (2^16)^6 Möglichkeiten.
        // Aufgrund des geringen Fehlers betrachten wir alle aktiven Eingänge als
        // einen Transistor. Widerstände in Reihe werden auf addiert.
        // Somit gilt für das Verhältnis:
        // 'n' = Anzahl aktiver Eingänge * R8 / R8
        // Unter dieser Annahme spielt es für die 4 voices in Hinsicht
        // auf die Konstante 'n' keine Rolle welche voices aktiv sind
        // sondern wie viele.        
        // Das ergiebt 5 Möglichkeiten: 0, 1, 2, 3 oder 4 voices aktiv
		
		int offset = 0;
		int size;
		for ( int k = 0; k < 5; k++ ) {
            // Anzahl aktiver Eingänge
			int idiv = 2 + k;
			int n_idiv = idiv << 7; // skaliert 2^7
			// Wir wollen für jede mögliche Summe beliebiger 'vi' 'vo' vor berechnen.
			size = idiv << 16;
			int x = ca.ak;
			for ( int vi = 0; vi < size; vi++ ) {
				// Die Spannungen der eingehenden voices werden addiert, zwecks Mischen.
				// Dadurch kann es passieren, dass der
				// Wertebereich überschritten (übersteuert) wird. Die Widerstände sollen
				// dies verhindern nach dem Prinzip (v1 + v2) / 2 (Amplitude halbieren)
                // Geschuldet der Tatsache, das wir alle aktiven Eingänge als einen
                // Transistor behandeln, teilen wir die Summe aller eingehenden Spannungen
                // durch die Anzahl Eingänge und ermitteln somit die Eingangsspannung
                // unseres fiktiven Transistors.
				ca.summer[offset + vi] = solveOpamp( ca.opamp, n_idiv, vi / idiv, x, ca );
			}
			// Jede Anzahl an Eingängen hat eine separate Vorberechnung.
			offset += size;
		}				

		// [ Impedanzwandler: Mixer ]
		// Der Mixer unmfasst 7 zuschaltbare Eingänge mit den selben
		// Einzel Widerständen 'R6'.
		// Es handelt sich mathematisch um die gleiche Logik wie beim Filter.
		// Inhaltlich werden voices direkt gemischt oder gefiltert gemischt.
		offset = 0;
        // Wenn kein Eingang aktiviert ist, gibt es nur den Zustand vi = 0 V
		size = 1;
		for ( int l = 0; l < 8; l++ ) {
			int idiv = l;
			// Der einzige mathematische Unterschied zum Filter besteht darin,
			// das der Widerstand um den Verstärker nicht den Einzelwiderständen
			// der Eingänge entspricht. Für das Verhältnis 'n' bedeutet das
			// R*8 ( Verstärker Widerstand ) / R*6 ( Vorwiderstand )
			int n_idiv = ( idiv << 7 ) * 8 / 6; // n*idiv, skaliert 2^7
			if ( idiv == 0 ) {
				// alle Eingänge sind deaktiviert
				// vi = 0, Wir setzen idiv = 1 um Division durch 0 zu verhindern
				// dennoch kein Fehler: vi / idiv = 0 / 1 = 0
				idiv = 1;
			}
			int x = ca.ak;
			for ( int vi = 0; vi < size; vi++ ) {
				ca.mixer[offset + vi] = solveOpamp( ca.opamp, n_idiv, vi / idiv, x, ca );
			}
			offset += size;
			size = ( l + 1 ) << 16;
		}
        
        // [ Impedanzwandler: multiple Eingänge ]
        // experimenteller Versuch alle Eingänge für Mixer und Filter als eigenständige Transistoren
        // zu berechnen. Leider lassen sich Terme nur teilweise vorberechnen.
        		        
		for ( int vi = 0; vi < (1 << 16); vi++ ) {
            ca.calcC[ vi ] = int( unsigned( ca.kVddt - vi ) * unsigned( ca.kVddt - vi ) >> 5 );
			ca.calcQ1[ vi ] = int(unsigned(vi) * unsigned(vi) >> 12);
            ca.calcQ2[ vi ] = int(unsigned(vi) * unsigned(vi) >> 5);
		}
        
        
		scaledVoltage.clear( );
        
        // Wir merken uns die mühsam errechneten Koordinaten für die Integratoren.
        // Diese können wir leider nicht vollständig vorberechnen.
        for (int i = 0; i < (1 << 16); i++)
            ca.opamp_rev[i] = ca.opamp[i].vx;           
        
		// Nachdem alle Impedanzwandler berechnet sind, benötigen wir noch einige
        // Vorberechnungen um die Integratoren später zur Laufzeit der emulation
        // zu berechnen.
		// Die Erklärung der Formeln befindet sich in der Datei 'opamp.cpp'
		// n = ucox/2k * dt/C        
        // 'C' beschreibt den außerhalb des Sid liegenden Kondensator.
        // dt = 1 Mikro Sekunde, Zeit Interval zur Betrachtung des Spannungs Verhalten am Kondensator
		// ucox/2k beschreibt die physikalischen Eigenschaften des Widerstandes
		// Um die Konstante in den Formeln zu verwenden, muss diese ebenfalls
		// übersetzt und skaliert werden.
		// Mir ist allerdings schleierhaft warum der Author hier mit 'denorm'
		// multipliziert. Ich hätte 'norm' erwartet oder 1 / denorm.
		// Später wird der Wert mit der Geometrie Konstante w/L multipliziert.
		// Möglicherweise wird dabei der Fehler wieder ausgeglichen.
		// Die Erklärung hierfür bleibe ich an dieser Stelle schuldig. 
        // skaliert auf 13 bit        
		ca.tmp_n_param = denorm * (1 << 13) * (pa.uCox / (2. * pa.k) * 1.0e-6 / pa.C); 		

        // Wir starten mit der Grenzfrequenz. Mitels Digital Analog Wandler werden
        // die im Register digitalen 11 bit in analoge Spannungen überführt.     
        unsigned int dacBits = 11;
        
		if ( m == 0 ) { // 6581
			// Genau wie für "envelope" und "voice" kommt ein R2R Netzwerk zum Einsatz.
			// Wie bei allen R2R Netzwerken des 6581 ist auch dieses nicht terminiert.
			// Genaue Erklärungen zur Berechnung des 'dac' befinden sich in 'dac.h'.
			// Resultat sind Spannungen in Abhängigkeit davon welche der 11 bits gesetzt
			// sind. Diese werden wiederum in einem 11 bit Ganzzahl Bereich dargestellt.
            Emulator::DAC<uint16_t> dac6581( dacBits, pa.dac_2R_div_R, pa.dac_term );
			dac6581.generate();
			            
			// Wir skalieren jede 11 bit Ganzzahl in eine Spannung, wobei wir wissen in welchem Bereich die Spannungen liegen.
			// Das Verhältnis ist:
			// dac Wert / x = 11 bit ( Ganzzahl Bereich) / 2.63 Volt (Spannungs Bereich)
            // x = dac Wert * pa.dac_scale / 11 bit = dac6581.get( n ) * pa.dac_scale / (1 << dacBits)            
			// Der Nullpunkt liegt bei 6.65 Volt.
			// Dann skalieren wir die normalisierte Spannung wie immer in einen 16 bit Ganzzahl Bereich.
			for (int n = 0; n < (1 << dacBits); n++)
				 ca.f0_dac[n] = (unsigned short)(N16 * (pa.dac_zero + dac6581.get( n ) * pa.dac_scale / (1 << dacBits) - vmin) + 0.5);			
			
			// Durch eine weitere Vorberechnung sparen wir uns das aufwendige Wurzel ziehen zur Laufzeit.
            // Vg = Vddt - sqrt(((Vddt - vi)^2 + (Vddt - Vw)^2) / 2)
            // Eine Erklärung der Formel befindet sich in 'opamp.cpp' unter 'solveIntegrate6581'            
            // y = Vddt - sqrt( x )            
            
			// Wir berechnen die Formel für jedes x.
            for (int i = 0; i < (1 << 16); i++) {
                // Die Wurzel wird aus einem 32 bit breiten Argument gezogen.
                // Durch das Wurzel ziehen halbiert sich der Bereich auf 16 bit.
                // Die unteren 16 bit füllen wir mit Nullen auf. 
				// Der ein oder andere Leser hat vielleicht mitbekommen, das 'kVddt'
				// nicht mittels Abzug von 'vmin' normalisiert wurde.
				// 'Vg' wird wie folgt weiter verwendet: k*(Vg - Vt) - Vx
				// (Vg - vmin) - (Vt - vmin)
				// 'vmin' neutralisiert sich, natürlich nur wenn 'Vt' ebenfalls
				// nicht normalisiert wird.
                double Vg = ca.kVddtWithoutVmin - std::sqrt((double) i * (1 << 16));
				// Der Faden ist jedoch noch nicht zu Ende gesponnen.
				// 'Vx' wird immer in normalisierter Form verwendet.
				// Das müssen wir ausgleichen um den Wert der Gleichung
				// nicht zu verändern.
				// kVg - kVt - vmin - (vx '- vmin')
				// Dies können wir gleich im Rahmen dieser Vorberechnung erledigen.
				// Somit müssen wir diesen Rechenschritt nicht mehr ständig
				// während der emulation durchführen.
                vcr_kVg[i] = (unsigned short)(pa.k * Vg - ca.vmin + 0.5);
            }           			

			// Nun berechnen wir das EKV Modell vor.
			// Wie gesagt, Formeln sind in 'opamp.cpp' erklärt.	
			// dt/C * Is * (if - ir)
			// Is = 2*u*Cox*Ut^2/k*W/L			
			// if = ln^2(1 + e^((k*(Vg - Vt) - Vs)/(2*Ut))
			// ir = ln^2(1 + e^((k*(Vg - Vt) - Vd)/(2*Ut))								
			// Die Vorberechnung gilt gleichermaßen für 'if' und 'ir',
			// da mathematisch identisch.
			// 'if' : dt/C * Is * if 
			// 'ir' : dt/C * Is * ir 
			double Ut = pa.Ut;
			double Is = 2 * pa.uCox * Ut * Ut / pa.k * pa.WL_vcr;
			// So geht es natürlich auch.
			double N15 = N16 / 2;
			// Die Konstante wird in 15 bit skaliert.
			double n_Is = N15 * 1.0e-6 / pa.C * Is;
			// Wie einige Zeilen früher erwähnt, haben wir 'Vg' nicht
			// mit 'vmin' normalisiert, mit dem Ziel 'Vt' ebenfalls nicht
			// normalisieren zu müssen.
			// k*(Vg - vmin - (Vt - vmin) ) 
			// In dem Fall neutralisiert sich 'vmin'
			double kVt = pa.k * pa.Vth;
			// 'kVg_Vx' = k * Vg - Vx
			// Die Vorberechnung wird für jeden möglichen Wert, den 'kVg_Vx'
			// annehmen kann, durchgeführt.
			// 'kVg_Vx': im Fall von 'if' entspricht 'Vx' -> 'Vs'
			// 'kVg_Vx': im Fall von 'ir' entspricht 'Vx' -> 'Vd'			
			// für alle Werte in einem Bereich von 16 bit vorberechnet
			for ( int kVg_Vx = 0; kVg_Vx < ( 1 << 16 ); kVg_Vx++ ) {
				// 'kVg_Vx' wird zuerst in eine Fließkomma Zahl zurück übersetzt,
				// da 'kVt' und 'Ut' ebenfalls nicht übersetzt bzw. skaliert sind.
				// 'exp' entspricht e^argument
				// 'log1p' entspricht ln( 1 + argument )
				double log_term = std::log1p( std::exp( ( kVg_Vx / N16 - kVt ) / ( 2 * Ut ) ) );
				// Laut Formel oben müssen wir noch das Quadrat bilden und mit 'dt/C * Is'
				// multiplizieren. Da alles ein Produkt ist gilt die Übersetzung/Skalierung
				// welche in 'Is' schon enthalten ist für den Rest mit.
				// sklaiert: m*2^15
				vcr_n_Ids_term[kVg_Vx] = (unsigned short) ( n_Is * log_term * log_term );
			}
			// vorberechnete Konstante, siehe 'opamp.cpp' unter 'solveIntegrate6581
			// n = w/l * ucox/2k * dt/C
			n_snake = (int)(pa.WL_snake * ca.tmp_n_param + 0.5);
			
        } else { // 8580
            // Der 11 bit DAC des 8580 besteht aus 11 parallelen Widerständen, welche per
			// bit zugeschalten werden. Im Gegesatz zum 6581 wird 'vi' direkt durch den
			// parallelen Gesamt Widerstand beeinflusst. 
			// Die per 'bit' zugeschaltenen Teil Widerstände sind verhältnis gleich
			// (proportional) zueinander. Für die Formel benötigen wir das Verhältnis W/L.
            // Da wir keine Spannung benötigen, lässt sich das R2R Netzwerk für den 
            // Geamt Widerstand jeder bit Kombination einfach wie folgt berechnen.
            unsigned short dacWL = 3; // 0.03125 * 32 FIXME actual value is ~= 0.003075
			// Ninja remix uses fc = 0 for intro music
			// ein NOR gate leitet die gate Spannung in den DAC
            ca.f0_dac[0] = dacWL; 
            
			// Wir berechnen die Werte für alle möglichen Grenzfrequenzen vor.
            for (int n = 1; n < (1 << dacBits); n++) {
                unsigned short wl = 0;
                for (unsigned int i = 0; i < dacBits; i++) {
                    unsigned int bitmask = 1 << i;
					// prüfen welche der bits gesetzt sind
                    if (n & bitmask) {
						// Gesamt Widerstand 
                        wl += dacWL * (bitmask << 1);
                    }
                }
                ca.f0_dac[n] = wl; // skaliert: 5 bit
            }
                        
            // Die Widerstände für die Grenzfrequenzen des 8580 haben eine andere Gate Spannung
            // als 'Vddt'. Die angelegte Spannung beträgt 7.6 Volt.
            // Effektivspannung errechnen, normalisieren 'vmin', in 16 bit Ganzzahl skalieren
            double Vgt = pa.k * ((4.75 * 1.6) - pa.Vth);
            // init value: seted in constructor 
            // kVgt = (int)(N16 * (Vgt - vmin) + 0.5);
        }      
	}

	delete[] voltages;       
}

// Register
// untere 3 bit der Grenzfrequenz
auto Sid::Filter::writeFcLow( uint8_t data ) -> void {
	fc = (fc & 0x7f8) | (data & 7);
    
    updateFrequency();
}
// obere 8 bit der Grenzfrequenz
auto Sid::Filter::writeFcHi( uint8_t data ) -> void {
	fc = ((data << 3) & 0x7f8) | (fc & 7);
    
    updateFrequency();
}
// 4 bit - Resonanz, 4 bit - Filter / Mixer Auswahl
auto Sid::Filter::writeResFilt( uint8_t data ) -> void {
	// Resonanz für Bandpass Filter
	res = ( data >> 4 ) & 0xf;
	// Steuert für alle 4 voices ( 1 - 3 ) + externe voice ob diese in den Filter
	// oder direkt in den Mixer geleitet wird. siehe v1 - ve im Schaltkreis
	filt = data & 0xf;
	
	updateSumMix();
    updateQ();
}

// 4 bit - Lautstärke, 4 bit - voice 3 Abschaltung, filter Resultate mixen
auto Sid::Filter::writeModeVol( uint8_t data ) -> void {
	// Steuert welche Filter Ausgänge gemixt werden. Außerdem kann
	// voice 3 komplett deaktivert werden, wenn in Register 0x17
	// für voice 3 keine Filterung gewählt wird.
	mode = data & 0xf0;
	// Master volume wird nach dem Mixer / Filter angewandt
	vol = data & 0xf;
    
    updateSumMix();
}

// wenn sich die Grenzfrequenz ändert, müssen wir ein paar Werte neu berechnen
auto Sid::Filter::updateFrequency() -> void {
    
    { // 6581
        Calculated& ca = calculated[0];
        // 'f0_dac' skaliert: 16 bit
        int Vw = Vw_bias + ca.f0_dac[fc];
		// Vorberechnung für: (Vddt - Vw)^2) / 2
		// siehe 'opamp.cpp' unter 'solveIntegrate6581
		// Normalisierung kürzt sich weg
		// Vddt - vmin - ( Vw - vmin ) = Vddt - Vw				
        Vddt_Vw_2 = unsigned(ca.kVddt - Vw) * unsigned(ca.kVddt - Vw) >> 1;
    }
        
    { // 8580
        Calculated& ca = calculated[1];
        // sklaiert: 13 + 5 = 18 bit
        int n_param = (int)(ca.tmp_n_param * 32 + 0.5);
        // skaliert: 18 + 5 - 10 = 13 bit
		// n = (ucox/2k * dt/C) * w/l
		// geänderter Widerstand w/l wird mit unveränderbarer Konstante vorberechnet
		// siehe 'opamp.cpp' unter 'solveIntegrate8580
        n_dac = (n_param * ca.f0_dac[ fc ]) >> 15;        
        
        w0 = 82355 * (fc + 1) >> 11;
    }
}

auto Sid::Filter::updateSumMix() -> void {
	
    // Filter Eingänge: bit 0: v1 , bit 1: v2 , bit 2: v3 , bit 3: ve
	// Übernahme der voices, welche in den Filter gelangen
	sum = (enabled ? filt : 0) & voiceMask; // filter summer
    // Mixer Eingänge: bit 0: v1 , bit 1: v2 , bit 2: v3 , bit 3: ve 
    // bit 4: tief pass , bit 5: band pass , bit 6: hoch pass
    // Damit 'mode' und 'mix' deckungsgleich sind, sind
    // die 4 mode bits um 4 bits nach links geschoben.
    
    // mode & 0x70 prüft für bit 4, 5, 6 ob die Filter Ausgänge in den Mixer gelangen
    // mode & 0x80 prüft ob voice 3 in den Mixer gelangt
    // alle '0' bits in 'filt' sind Mixer Eingänge
    // wenn voice 3 deaktiviert, interessiert uns das entsprechende bit in 'filt' nicht
    // also voice 3 geht nur direkt in den Mixer, wenn bit 2 in 'filt' 0 ist und
    // wenn bit 7 in 'mode' 0 ist
    
    if (enabled) {
        mix = (mode & 0x70) | ( (~(filt | (mode & 0x80) >> 5)) & 0x0f );    
        
    } else {
        // Das ist keine Option des Sid Chips, sondern im Rahmen
        // der emulation die Möglichkeit den filter unabhängig von der
        // Software zu deaktivieren.
        // voice 3 wird nur deaktivert, wenn es per Register für filter
        // und mixer deaktiviert ist, also die Software voice 3 komplett
        // deaktiviert hat.
        if ( (mode & 0x80) && !(filt & 4) )
            mix = 0xb; // alle voices außer voice 3 gehen ungefiltert in den Mixer
        else
            mix = 0xf; // alle voices gehen ungefiltert in den Mixer
    }
    
    mix &= voiceMask;
    
    if (sid->moreAccuracy)
        multiPrecalculate();
}

auto Sid::Filter::setType( Type type ) -> void {
    // Sid Modell auswählen
	this->type = type;
	// Werte initialisieren, für den Fall das das Sid Model zur Laufzeit
	// geändert wird.
	Vhp = 0;
	Vbp = Vbp_x = Vbp_vc = 0;
	Vlp = Vlp_x = Vlp_vc = 0;
}

// Filter kann unabhängig von der Software deakiviert werden.
auto Sid::Filter::setEnable( bool state ) -> void {
	enabled = state;
	
	updateSumMix();
}

auto Sid::Filter::updateQ() -> void {
    // gilt nur für 6581
    // Wie oben erklärt, müssen wir die Register bits für Resonanz invertieren
    // um die Vorberechnung für Lautstärke nutzen zu können.
    _8_div_Q = ~res & 0x0f;
    
    static const int _1024_div_Q_table[] = {
        1448,
        1328,
        1218,
        1117,
        1024,
        939,
        861,
        790,
        724,
        664,
        609,
        558,
        512,
        470,
        431,
        395
    };

    _1024_div_Q = _1024_div_Q_table[res];
}

auto Sid::Filter::setVoiceMask( uint8_t mask ) -> void {
    // Wird normalerweise dazu benuzt 've' zu deaktivieren.
    // Es können jedoch alle anderen voices ebenso deaktiviert
    // werden.
    voiceMask = 0xf0 | (mask & 0x0f);
    
    updateSumMix();
}

auto Sid::Filter::reset() -> void {
    fc = 0;
    res = 0;
    filt = 0;
    mode = 0;
    vol = 0;

    Vhp = 0;
    Vbp = Vbp_x = Vbp_vc = 0;
    Vlp = Vlp_x = Vlp_vc = 0;

    updateFrequency();
    updateQ();
    updateSumMix();
}

// Hierüber lässt sich die Zenter Frequenz, welche als user input in die
// emulation gelangt, anpassen. Dies ermöglicht fertigungsbedingte
// Unterschiede des Sid 6581 Filter zu simulieren. Auf den 8580 hat dies
// keinen nennenswerten Einfluß.
// Wir wiederholen die entsprechnenden Vorberechnungen.
auto Sid::Filter::adjustFilterBias6581(int value) -> void {
    bias6581 = value;
    
    double dac_bias = (double)value / 1000.0;
    
	// 6581
	Vw_bias = int( dac_bias * calculated[0].vo_N16);
	updateFrequency();
}

auto Sid::Filter::adjustFilterBias8580(int value) -> void {
    bias8580 = value;
    
    double dac_bias = (double)value / 1000.0;    

	// 8580
	// geänderte gate Spannung nach obiger Formel neu ausrechnen
	// Ua = Ue * v = 4.75v  1<v<2
	double Vg = 4.75 * (dac_bias * 6./100. + 1.6);
	double Vgt = parameter[1].k * (Vg - parameter[1].Vth);
	double vmin = parameter[1].opampVoltage[0][0];

	kVgt = (int)(calculated[1].vo_N16 * (Vgt - vmin) + 0.5);
 
}

}

