
//  This code is a modification of the reSID engine in VICE
//  You can get a copy of the original here: https://sourceforge.net/projects/vice-emu/

//  ---------------------------------------------------------------------------
//  This file is part of VICE, the Versatile Commodore Emulator.
//  This file is part of reSID, a MOS6581 SID emulator engine.
//  Copyright (C) 2010  Dag Lem <resid@nimrod.no>
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//  ---------------------------------------------------------------------------

#include "../sid.h"

#include <vector>
#include <thread>

namespace LIBC64 {

doublePoint Sid::Filter::opamp6581[] = {
	{ 0.81, 10.31 }, // vmin, vmax
	{ 0.81, 10.31 }, // Repeated point
	{ 2.40, 10.31 },
	{ 2.60, 10.30 },
	{ 2.70, 10.29 },
	{ 2.80, 10.26 },
	{ 2.90, 10.17 },
	{ 3.00, 10.04 },
	{ 3.10, 9.83 },
	{ 3.20, 9.58 },
	{ 3.30, 9.32 },
	{ 3.50, 8.69 },
	{ 3.70, 8.00 },
	{ 4.00, 6.89 },
	{ 4.40, 5.21 },
	{ 4.54, 4.54 }, // Working point (vi = vo)
	{ 4.60, 4.19 },
	{ 4.80, 3.00 },
	{ 4.90, 2.30 }, // Change of curvature
	{ 4.95, 2.03 },
	{ 5.00, 1.88 },
	{ 5.05, 1.77 },
	{ 5.10, 1.69 },
	{ 5.20, 1.58 },
	{ 5.40, 1.44 },
	{ 5.60, 1.33 },
	{ 5.80, 1.26 },
	{ 6.00, 1.21 },
	{ 6.40, 1.12 },
	{ 7.00, 1.02 },
	{ 7.50, 0.97 },
	{ 8.50, 0.89 },
	{ 10.00, 0.81 },
	{ 10.31, 0.81 }, // Approximate end of actual range
	{ 10.31, 0.81 } // Repeated end point
};

doublePoint Sid::Filter::opamp8580[] = {
	{ 1.30, 8.91 }, // vmin, vmax
	{ 1.30, 8.91 }, // Repeated end point
	{ 4.76, 8.91 },
	{ 4.77, 8.90 },
	{ 4.78, 8.88 },
	{ 4.785, 8.86 },
	{ 4.79, 8.80 },
	{ 4.795, 8.60 },
	{ 4.80, 8.25 },
	{ 4.805, 7.50 },
	{ 4.81, 6.10 },
	{ 4.815, 4.05 }, // Change of curvature
	{ 4.82, 2.27 },
	{ 4.825, 1.65 },
	{ 4.83, 1.55 },
	{ 4.84, 1.47 },
	{ 4.85, 1.43 },
	{ 4.87, 1.37 },
	{ 4.90, 1.34 },
	{ 5.00, 1.30 },
	{ 5.10, 1.30 },
	{ 8.91, 1.30 }, // Approximate end of actual range
	{ 8.91, 1.30 } // Repeated end point
};

Sid::Filter::Parameter Sid::Filter::parameter[2] = {
	{
		opamp6581,
		sizeof (opamp6581 ) / sizeof (*opamp6581 ),
		// The dynamic analog range of one voice is approximately 1.5V,
		1.5,
		// riding at a DC level of approximately 5.0V.
		5.075,
		// Capacitor value.
		470e-12,
		// Transistor parameters.
		12.18,
		1.31,
		26.0e-3,
		1.0,
		20e-6,
		9.0 / 1.0,
		1.0 / 115,
		// DAC parameters.
		6.65,
		2.63,
		2.20,
		false
	},
	{
		opamp8580,
		sizeof (opamp8580 ) / sizeof (*opamp8580 ),
		// FIXME: Measure for the 8580.
		0.24,
		// The 4.75V voltage for the virtual ground is generated by a PolySi resistor divider
		4.7975,
		// Capacitor value.
		22e-9,
		// Transistor parameters.
		9.09,
		0.80,
		26.0e-3,
		1.0,
		100e-6,
		// FIXME: 6581 only
		0,
		0,
		0,
		0,
		2.00,
		true
	}
};

Sid::Filter::Calculated Sid::Filter::calculated[2] = { {0}, {0} };

unsigned short Sid::Filter::vcr_kVg[1 << 16];
unsigned short Sid::Filter::vcr_n_Ids_term[1 << 16];

int Sid::Filter::n_snake = 0;

Sid::Filter::Filter( Sid* sid ) {
    this->sid = sid;
	static bool initialized = false;
    digiBoost = false;

	if ( !initialized ) {
		std::thread t1(Sid::Filter::build, 0);
		build(1);
		t1.join();

		initialized = true; // one time only, doesn't matter of instance count
	}

	v1P = &v1;
	v2P = &v2;
	v3P = &v3;
	veP = &ve;
	VhpP = &Vhp;
	VlpP = &Vlp;
	VbpP = &Vbp;
	VbpResP = &VbpRes;
	
	Vw_bias = 0; 
    setEnable( true );
    setType( MOS_6581 );
    setVoiceMask( 7 ); // 've' disabled
    adjustFilterBias6581(500);
    adjustFilterBias8580(0);
    input(0);
    reset();    
}

auto Sid::Filter::build(int m) -> void {
	unsigned int* voltages = new unsigned int[ 1 << 16 ];

	//for ( unsigned m = 0; m < 2; m++ ) { // m = 0 -> 6581, m = 1 -> 8580
		Parameter& pa = parameter[m];
		Calculated& ca = calculated[m];
		// obige Tabellen zeigen einige Messpunkte am Original
		// aus vorhandenen Messpunkten auf weitere dazwischen liegende schlußfolgern
		// erste Messpunkt beschreibt die geringste gemessene Eingangsspannung
		double vmin = pa.opampVoltage[0][0];
		// durch Invertierung ergiebt sich die dazu höchst gemessene Ausgangsspannung
		double opampMax = pa.opampVoltage[0][1];
		// Vdd ist die Gesamtspannung welche dem Stromkreis als Gleichspannung angelegt ist. Vth (Threshold) ist die Minimal Spannung,
		// welche notwendig ist damit der Stromkreis überhaupt funktioniert. Die Effektiv Spannung ist demnach die Gesamt Spannung
		// weniger der Grenz Spannung. Diese Spannung kann der op-amp nicht überschreiten.
		// Durch den Material Faktor 'k' verringert sich die Effektiv Spannung etwas.
		double kVddt = pa.k * ( pa.Vdd - pa.Vth );
		double vmax = kVddt < opampMax ? opampMax : kVddt;
		// In diesem Spannungs Bereich arbeitet der op-amp.
		double denorm = vmax - vmin;
		// normalisieren um später in verschiedene ganz zahlige Bereiche skalieren zu können
		double norm = 1.0 / denorm;
		// Spannungen werden als Gleitkommazahlen dargestellt.
		// Um die Spannung in eine Ganzzahl zu übersetzen, benötigt man die Maximal Differenz "denorm" aus kleinster und größter Spannung.
		// Die Maximal Differenz entspricht dabei der größt möglichen Ganzzahl des Ziel Bereiches.
		// Im selben Verhältnis lassen sich alle Werte skalieren.
		// denorm / x = (2^n bits - 1) / y  umgestellt: y = (x * (2^n bits - 1) ) / denorm
		// oder y = x * (2^n bits - 1) * norm
		double N16 = norm * ( ( 1u << 16 ) - 1 ); // 16 bit
		ca.vo_N16 = N16;

		// Mehr bits bedeutet eine höhere Genauigkeit. Somit lassen sich immer feinere Unterschiede in den Spannungen Ganzzahlen zuordnen.
		// Je begrenzter die Genauigkeit desto eher steht die selbe Ganzzahl für verschiedene Spannungen.		
		double N30 = norm * ( ( 1u << 30 ) - 1 ); // 30 bit
		double N31 = norm * ( ( 1u << 31 ) - 1 ); // 31 bit
		double N14 = norm * ( 1u << 14 );
        // verschieden skalierete Werte können mit einander multipliziert oder dividiert werden. Dadurch ändert sich die Skalierung
        // des Produktes bzw des Quotienten. Addition bzw. Subtraktion erhält die Skalierung aber beide Seiten müssen gleich skaliert sein.
        // z.B. 2^16 * 2^16 = 2^(16+16) = 2^32, 2^30 / 2^14 = 2^(30-14) = 2^16
        
		// Ausgangspunkt sind die voice ( 12 bit ) und dazu gehörige envelope ( 8 bit ). Envelope moduliert die amplitude der voice,
		// eine Art Lautstärke Umschlag. Die dafür notwendige Multiplikation ergibt eine maximale digitale Spanne von 20 bits für die voice.
		// Eine Voice bewegt sich in einem Intervall von 1.5 V (6581). Betrag aus negativer und positiver Spannung |-V| + |V| = 1.5 V,
		// heißt die 20 bits beschreiben die Abstufungen in diesem Interval.
		// 1,5 Volt in 16 bit Ganzzahl skalieren
		// scale_1.5 = N16 * 1.5 V (6581)
		// 20 bit voice in 1.5 Volt Spanne skalieren
		// scale_1.5 / x = 2^20 / voice
		// x = voice * scale_1.5 / 2^20
		// x = voice * N16 * 1.5 V / 2^20
		// Leider übersteigt die Multiplikation den Wertebereich von int und c++ erwartet eine long long Konvertierung.
		// Um eine long long Konvertierung zu vermeiden, dürfen keine Zwischenergebnisse 32 bit überschreiten.
		// Skalierung in einen kleineren Bereich: N14 reicht aus. Um den Wert der Gleichung nicht zu verändern, wird durch 2^18 anstatt 2^20 geteilt.
		// x = voice * N14 * 1.5 V / 2^18
		ca.voiceScaleS14 = (int) ( N14 * pa.voiceVoltageRange );
        if (m == 1)
            ca.voiceScaleS14Old = (int) ( N14 * 1.0 ); // reSID 2.4 support
		// Neben dem Multiplikator um eine beliebige voice in Ziel Bereich zu skalieren, wird noch der Nullpunkt benötigt,
		// zu welchem die voice auf addiert wird.
		// Die voice ist vorzeichenbehaftet und wird den Nullpunkt unterschreiten bzw. überschreiten.
		// Natürlich muss auch die Nullpunkt Spannung in einen 16 bit breiten Ganzzahl Bereich skaliert werden.
        // Der Bereich in den skaliert wird, betrachtet 'vmin' als kleinst möglichen Wert anstatt 0 Volt.
        // Am Chip gemessene Spannungen müssen erst in den Bereich vmin <-> vmax vor der Skalierung übersetzt werden.
        // Dies geschieht einfach durch Abzug von 'vmin'.
		ca.voiceDC = (int) ( N16 * ( pa.voiceDCVoltage - vmin ) );
        if (m == 1)
            ca.voiceDCOld = (int) ( N16 * ( 1.30 - vmin ) ); // reSID 2.4 support
		
		// skalierte Ganzahl für die Effektivspannung
		ca.kVddt = (int) ( N16 * ( kVddt - vmin ) + 0.5 ); // aufrunden
		ca.kVddtWithoutVmin = N16 * kVddt;
		ca.vmin = N16 * vmin;
		
		// Obige Messpunkte für Ein- und Ausgangsspannung der op-amps sind zwar schon sehr ausführlich aber skaliert in einen 16 bit
		// Ganzzahl Bereich fehlen doch etliche Zwischenwerte. fehlende Punkte werden durch Interpolation ergänzt.
		// Ziel ist es einen harmonischen Kurvenverlauf durch die bestehenden Punkte zu führen und somit die fehlenden 
		// zu ermitteln. mapping für X und Y im Koordinatensystem: vo - vx -> vx
		// X-Achse: delta der Spannungen vor und nach der Verstärkung
		// Y-Achse: Spannung vor der Operationsverstärkung

		std::vector<Emulator::Coordinate> scaledVoltage;
		// Für alle Messpunkte werden Koordinaten generiert.
		for ( int i = 0; i < pa.opampVoltageSize; i++ ) {
			Emulator::Coordinate coordinate;
			// X-Achse:
			// Zuerst wird das Spannungs delta jedes einzelnen Messpunktes ermittelt, dann wird skaliert.
			// 'vmin' kürzt sich weg: (Vout - vmin) - (Vin - vmin)
			coordinate.x = N16 * ( pa.opampVoltage[i][1] - pa.opampVoltage[i][0] ) / 2.0;
			// negative offsets im Feld verhindern. später an Rück übersetzung denken
			coordinate.x += double(1 << 15);
			// Y-Achse: Eingangsspannung für mehr Genauigkeit auf eine größere Anzahl bits skalieren
			coordinate.y = N31 * ( pa.opampVoltage[i][0] - vmin );
			// für aufsteigende X-Werte Reihenfolge der Koordinaten invertieren
			scaledVoltage.insert( scaledVoltage.begin( ), coordinate );
		}

		// Durch Aufrundung kann der Wertebereich überschritten werden, somit muss auf den letzten Wert abgeschnitten werden.
		if ( scaledVoltage[ scaledVoltage.size( ) - 1].x > 65535.0 ) {
			// ebenso vorletzte Koordinate, da wiederholt  (siehe obige Tabelle)
			scaledVoltage[ scaledVoltage.size( ) - 1].x = scaledVoltage[ scaledVoltage.size( ) - 2].x = 65535.0;
		}

		// Die durch die Interpolation ermittelten Werte sind Ganzahlen, welchen Spannungen als Gleitkommazahlen zugewiesen sind.
		// X-Richtung Schrittgröße: 1.0
		Emulator::CatmullSpline::interpolate( scaledVoltage, Emulator::PointPlotter<unsigned int>( voltages ), 1.0 );

		ca.ak = (int)(scaledVoltage[0].x + 0.5); // Minimum
		ca.bk = (int)(scaledVoltage[scaledVoltage.size( ) - 1].x + 0.5); // Maximum

		// Initialisierung
		int j;
		for ( j = 0; j < ca.ak; j++ ) {
			// Spannung 'vx' vor der Verstärkung
			ca.opamp[j].vx = 0;
			// Differenz direkt aufeinander folgender Spannungen 'vx'
			ca.opamp[j].dvx = 0;
		}
		// voltages erhält das Ergebnis der Interpolation
		unsigned int f = voltages[j]; //erster Wert

		for (; j < ca.bk; j++ ) {
			unsigned int fp = f;
			f = voltages[j];
			// delta zwischen aufeinander folgenden Y-Werten.
			// skaliert : (m * 2^31 * dy) / (m * 2^16 * dx) = 2^15 * dy/dx
			// 15 bits + Vorzeichen Bit
			int df = f - fp;
			// Die Werte der Y-Achse werden zurück auf vorzeichenlose 16 bit skaliert (31 - 15)		
			ca.opamp[j].vx = f > ( 0xffff << 15 ) ? 0xffff : f >> 15;
			// skaliert : 2^11 um 'long long' Konvertierungen bei der Weiterverwendung zu vermeiden
			ca.opamp[j].dvx = df >> ( 15 - 11 );
		}
		for (; j < ( 1 << 16 ); j++ ) {
			ca.opamp[j].vx = 0;
			ca.opamp[j].dvx = 0;
		}
		// Es fehlt das delta für den Start Wert.
		ca.opamp[ ca.ak ].dvx = ca.opamp[ ca.ak + 1 ].dvx;

        // Neben obigen Messpunkten sind nun Werte für beliebige Spannungen am op-amp vorhanden.
		// Alle Impedanzwandler im Schaltkreis haben einen Vorwiderstand R1 und einen prallel zum 
		// Operationsverstärker geschaltenen Widerstand R2.
		// Bei einer Parallelschaltung liegt an allen Verbrauchern die gleiche Spannung an.
		// Somit liegt auch am Widerstand R2 die Spannung des op-amp an.
		// 'vx' ist die Spannung vor der Verstärkung in Spalte 1 der obigen Tabellen
		// 'vo' ist die Ausgangs Spannung nach der Verstärkung in Spalte 2
		// 'vi' ist die Eingangs Spannung an R1
		// die Schwierigkeit ist jetzt anhand der Eingangsspannung 'vi' auf die richtige vorberechnete
		// Ausgangsspannungen 'vo' zu schlußfolgern, siehe Funktion 'solveOpamp'

		// [ Impedanzwandler: Lautstärke und Resonanz 6581 ]
		// Lautstärke und bandpass Resonanz des 6581 haben das gleiche mathematische Modell. Beide werden durch 4 bits (16 Zustände)
		// gesteuert und die zuschaltbaren Vor Widerstände sind: 8*R (bit 0), 4*R (bit 1), 2*R (bit 2), 1*R (bit 3)
		// siehe 'circuit' op-amp [A> direkt vor 'Audio out'
		double divider = m == 0 ? 12.0 : 16.0;
		for ( int n8 = 0; n8 < 16; n8++ ) {
			// Die Funktion 'solveOpamp' erwartet für 'n' das Verhältnis der Geometrie
			// des Gesamt Widerstandes R1 (aller zuschaltbaren) und des Widerstandes R2 um den Verstärker.
            // In der Funktion 'solveOpamp' ist hergeleitet, das man für 'n' = R2 / R1 schreiben kann.
			// x = Verhältnis zwischen R1 und R2
			// bit 0 (n8 == 1) = x/8
            // bit 1 (n8 == 2) = x/4 = 2x/8
            // bit 2 (n8 == 4) = x/2 = 4x/8
			// bit 3 (n8 == 8) = x/1 = 8x/8
            // sind mehrere 'R1' parallel geschalten, gilt die Formel für parallele
            // Widerstände: 1 / Rges = 1 / Rx + 1 / Ry + 1 / Rz ...
            // sind z.B. bit 0 und bit 1 (n8 = 3) gesetzt: 1 / R1 = 1 / 8 + 1 / 4
            // 1 / R1 = 3 / 8 => R1 = 8 / 3
			// R2 / R1 = x / (8 / 3) = 3x / 8
			double n = double(n8) / divider;
			// kleinster Startwert für Newton-Raphson Verfahren, siehe 'solveOpamp'
			int x = ca.ak;
			// ermitteln für alle 'vi' das zugehörige 'vo' in Abhängigkeit von 'vx'
			for ( int vi = 0; vi < ( 1 << 16 ); vi++ ) {
				ca.gain[n8][vi] = solveOpamp( ca.opamp, n, vi, x, ca );
			}
		}

		if (m == 0) { // Resonanz 6581
			// Beachtet werden muss, dass im Gegensatz zur Lautstärke die gesetzten bits eine Stromfluss Unterbrechung bedeuten,
			// siehe Resonanz -> 1 = open und Lautstärke -> 0 = open.
			// R1 = R2 => x = 1
			for ( int n8 = 0; n8 < 16; n8++ ) {
				int x = ca.ak;
				int x2 = ca.ak;
				double n = double(~n8 & 0xf) / 8.0;

				for (int vi = 0; vi < (1 << 16); vi++) {
					ca.resonance[n8][vi] = solveOpamp(ca.opamp, n, vi, x, ca);
				}
			}
		}
        // Laut Schaltkreis für den 8580 weicht die Resonanz Schaltung vom 6581 ab.
        // Zum einem sind die Widerstände von bit Kombinationen abhängig anstatt Einzel bits
        // zum anderen sind mehrere Widerstände parallel zum Verstärker geschalten und ebenso
        // von bit Kombinationen abhängig. Im Schaltkreis des 8580 ist dargestellt,
		// welche bits welche Widerstände zuschalten. 'Rf' ist immer aktiv.		
		// Der Gesamt Widerstand von genau 2 parallel geschaltenen Einzelwiderständen berechnet sich:
        // Rges = (Rx * Ry) / (Rx + Ry)
        // n = Gesamt Widerstand parallel zum Verstärker / Widerstand davor
        // Der Vor Widerstand kann immer nur genau einer der 4 sein, siehe bits D6 u. D7.
		
		// Ri = 1.0
		// R1 = 15.3*Ri
		// R2 =  7.3*Ri
		// R3 =  4.7*Ri
		// Rf =  1.4*Ri
		// R4 =  1.4*Ri
		// R8 =  2.0*Ri
		// RC =  2.8*Ri

		if (m == 1) {
			double resGain[16] ={
				((1.4 / 1.0)), //      Rf/Ri   1.4
				((((1.4 * 15.3) / (1.4 + 15.3)) / 1.0)), // (Rf|R1)/Ri   1.28263
				((((1.4 * 7.3) / (1.4 + 7.3)) / 1.0)), // (Rf|R2)/Ri   1.17471
				((((1.4 * 4.7) / (1.4 + 4.7)) / 1.0)), // (Rf|R3)/Ri   1.07869
				((1.4 / 1.4)), //      Rf/R4   1.0
				((((1.4 * 15.3) / (1.4 + 15.3)) / 1.4)), // (Rf|R1)/R4   0.916168
				((((1.4 * 7.3) / (1.4 + 7.3)) / 1.4)), // (Rf|R2)/R4   0.83908
				((((1.4 * 4.7) / (1.4 + 4.7)) / 1.4)), // (Rf|R3)/R4   0.770492
				((1.4 / 2.0)), //      Rf/R8   0.7
				((((1.4 * 15.3) / (1.4 + 15.3)) / 2.0)), // (Rf|R1)/R8   0.641317
				((((1.4 * 7.3) / (1.4 + 7.3)) / 2.0)), // (Rf|R2)/R8   0.587356
				((((1.4 * 4.7) / (1.4 + 4.7)) / 2.0)), // (Rf|R3)/R8   0.539344
				((1.4 / 2.8)), //      Rf/RC   0.5
				((((1.4 * 15.3) / (1.4 + 15.3)) / 2.8)), // (Rf|R1)/RC   0.458084
				((((1.4 * 7.3) / (1.4 + 7.3)) / 2.8)), // (Rf|R2)/RC   0.41954
				((((1.4 * 4.7) / (1.4 + 4.7)) / 2.8)), // (Rf|R3)/RC   0.385246
			};

			for (int n8 = 0; n8 < 16; n8++) {
				int x = ca.ak;
				for (int vi = 0; vi < (1 << 16); vi++) {
					ca.resonance[n8][vi] = solveOpamp(ca.opamp, resGain[n8], vi, x, ca);
				}
			}
		}

		// [ Impedanzwandler: hoch pass ]
		// tief pass und band pass Eingänge sind immer zugeschalten ( die beiden obersten 'R8')
		// die 3 voices + externe voice sind zuschaltbar.
        // Problem ist hier, das es mehr als einen Spannungs Eingang gibt.
        // Berechnungsformel, siehe 'solveOpamp', ist nur für einen Eingang ausgelegt.
        // Das Widerstandsverhältnis ergiebt für einen Eingang: R8 / R8 = 1
        // Richtigerweise müsste jeder Transistor für sich berechnet werden, da
        // diese sich nicht exakt linear verhalten.
        // Jedoch wird es dann problematisch die Werte vorzuberechnen.
        // Falls alle 6 Eingänge aktiv sind, weist jeder Eingang eine individuelle
        // Spannung auf. Das ergibt (2^16)^6 Möglichkeiten.
        // Aufgrund des geringen Fehlers werden alle aktiven Eingänge als ein Transistor betrachtet.
        // Widerstände in Reihe werden auf addiert.
        // Somit gilt für das Verhältnis:
        // 'n' = Anzahl aktiver Eingänge * R8 / R8
        // Unter dieser Annahme spielt es für die 4 voices in Hinsicht
        // auf die Konstante 'n' keine Rolle, welche voices aktiv sind sondern wie viele.
        // Das ergiebt 5 Möglichkeiten: 0, 1, 2, 3 oder 4 voices aktiv.
		
		int offset = 0;
		int size;
		for ( int k = 0; k < 5; k++ ) {
            // Anzahl aktiver Eingänge
			int idiv = 2 + k; // tief pass und band pass Eingänge sind immer zugeschalten
			double n_idiv = double(idiv);
			size = idiv << 16;
			int x = ca.ak;
			for ( int vi = 0; vi < size; vi++ ) {
				// Die Spannungen der eingehenden voices werden addiert, zwecks Mischen.
				// Dadurch kann es passieren, dass der Wertebereich überschritten (übersteuert) wird.
				// Die Widerstände sollen dies verhindern nach dem Prinzip (v1 + v2) / 2 (Amplitude halbieren)
                // Geschuldet der Tatsache, das alle aktiven Eingänge als ein Transistor behandelt werden,
                // wird die Summe aller eingehenden Spannungen durch die Anzahl Eingänge geteilt und ermittelt
                // somit die Eingangsspannung des fiktiven Transistors.
				ca.summer[offset + vi] = solveOpamp( ca.opamp, n_idiv, vi / idiv, x, ca );
			}
			// Jede Anzahl an Eingängen hat eine separate Vorberechnung.
			offset += size;
		}				

		// [ Impedanzwandler: Mixer ]
		// Der Mixer unmfasst 7 zuschaltbare Eingänge.
		divider = m == 0 ? 6.0 : 5.0;
		offset = 0;
		size = 1;
		for ( int l = 0; l < 8; l++ ) {
			int idiv = l;
			double n_idiv = double(idiv << 3)/divider; // n*idiv

			if ( idiv == 0 ) {
				// alle Eingänge sind deaktiviert
				// vi = 0, idiv = 1 um Division durch 0 zu verhindern
				idiv = 1;
			}
			int x = ca.ak;

			for ( int vi = 0; vi < size; vi++ ) {
				ca.mixer[offset + vi] = solveOpamp( ca.opamp, n_idiv, vi / idiv, x, ca );
			}
			offset += size;
			size = ( l + 1 ) << 16;
		}

		scaledVoltage.clear( );

        for (int i = 0; i < (1 << 16); i++)
            ca.opamp_rev[i] = ca.opamp[i].vx;

        // Vorberechnungen um die Integratoren später zur Laufzeit der Emulation zu berechnen.
		// n = ucox/2k * dt/C        
        // 'C' beschreibt den außerhalb des SID liegenden Kondensator.
        // dt = 1 Mikro Sekunde, Zeit Interval zur Betrachtung des Spannungs Verhalten am Kondensator
		// ucox/2k beschreibt die physikalischen Eigenschaften des Widerstandes
		// Vorberechnung des konstanten Anteils der Formel zur Filterung
        // skaliert auf 13 bit
		// denorm = 1 / norm ; Die Konstante wird mit dem Quadrat skalierter Spannungen multipliziert.
		// m*2^16 * m*2^16 = m^2*2^32
		// Die Skalierung wird dann korrigiert: m^2*2^32 * (denorm: 1/m) = m*2^32
		ca.tmp_n_param = denorm * (1 << 13) * (pa.uCox / (2. * pa.k) * 1.0e-6 / pa.C); 		

        unsigned int dacBits = 11;
        
		if ( m == 0 ) { // 6581
            Emulator::DAC<uint16_t> dac6581( dacBits, pa.dac_2R_div_R, pa.dac_term );
			dac6581.generate();

			for (int n = 0; n < (1 << dacBits); n++)
				 ca.f0_dac[n] = (unsigned short)(N16 * (pa.dac_zero + dac6581.get( n ) * pa.dac_scale / (1 << dacBits) - vmin) + 0.5);			

            // Vg = Vddt - sqrt(((Vddt - vi)^2 + (Vddt - Vw)^2) / 2)
            // y = Vddt - sqrt( x )            

            for (int i = 0; i < (1 << 16); i++) {
				// 'kVddt' wird nicht mittels Abzug von 'vmin' normalisiert.
				// 'Vg' wird wie folgt weiter verwendet: k*(Vg - Vt) - Vx
				// (Vg - vmin) - (Vt - vmin)
				// 'vmin' neutralisiert sich somit.
                double Vg = ca.kVddtWithoutVmin - std::sqrt((double) i * (1 << 16));
				// 'Vx' wird immer in normalisierter Form verwendet.
                vcr_kVg[i] = (unsigned short)(pa.k * Vg - ca.vmin + 0.5);
            }           			

			// Berechnung EKV Modell
			// dt/C * Is * (if - ir)
			// Is = 2*u*Cox*Ut^2/k*W/L			
			// if = ln^2(1 + e^((k*(Vg - Vt) - Vs)/(2*Ut))
			// ir = ln^2(1 + e^((k*(Vg - Vt) - Vd)/(2*Ut))								
			// Die Vorberechnung gilt gleichermaßen für 'if' und 'ir', da mathematisch identisch.
			// 'if' : dt/C * Is * if 
			// 'ir' : dt/C * Is * ir 
			double Ut = pa.Ut;
			double Is = 2 * pa.uCox * Ut * Ut / pa.k * pa.WL_vcr;
			double N15 = N16 / 2;
			double n_Is = N15 * 1.0e-6 / pa.C * Is;
			// Vg' wird nicht mit 'vmin' normalisiert, mit dem Ziel 'Vt' ebenfalls nicht normalisieren zu müssen.
			// k*(Vg - vmin - (Vt - vmin) ) 
			// In dem Fall neutralisiert sich 'vmin'
			double kVt = pa.k * pa.Vth;
			// 'kVg_Vx' = k * Vg - Vx
			// 'kVg_Vx': im Fall von 'if' entspricht 'Vx' -> 'Vs'
			// 'kVg_Vx': im Fall von 'ir' entspricht 'Vx' -> 'Vd'
			for ( int i = 0; i < ( 1 << 16 ); i++ ) {
				int kVg_Vx = i - (1 << 15);
				// 'kVg_Vx' wird in eine Fließkomma Zahl zurück übersetzt,
				// da 'kVt' und 'Ut' ebenfalls nicht übersetzt bzw. skaliert sind.
				// 'exp' entspricht e^argument
				// 'log1p' entspricht ln( 1 + argument )
				double log_term = std::log1p( std::exp( ( kVg_Vx / N16 - kVt ) / ( 2 * Ut ) ) );
				// sklaiert: m*2^15
				vcr_n_Ids_term[i] = (unsigned short) ( n_Is * log_term * log_term );
			}

			// n = w/l * ucox/2k * dt/C
			n_snake = (int)(pa.WL_snake * ca.tmp_n_param + 0.5);
			
        } else { // 8580
            // Der DAC des 8580 besteht aus 11 parallelen Widerständen, welche per
			// Bit zugeschalten werden. Im Gegesatz zum 6581 wird 'vi' direkt durch den
			// parallelen Gesamt Widerstand beeinflusst. 
			// Die zugeschaltenen Teil Widerstände sind verhältnis gleich (proportional) zueinander.
        	unsigned int dacWL = 806; // 0,00307464599609375 * 1024 * 256 (actual value is ~= 0.003075)
			// ein NOR gate leitet die gate Spannung in den DAC
            ca.f0_dac[0] = dacWL >> 8;

            for (int n = 1; n < (1 << dacBits); n++) {
                unsigned int wl = 0;
                for (unsigned int i = 0; i < dacBits; i++) {
                    unsigned int bitmask = 1 << i;
                    if (n & bitmask) {
						// Gesamt Widerstand 
                        wl += dacWL * (bitmask << 1);
                    }
                }
                ca.f0_dac[n] = wl >> 8; // skaliert: 18 - 8 = 10 bit
            }
        }      
	//}

	delete[] voltages;       
}

// Register
// untere 3 bit der Grenzfrequenz
auto Sid::Filter::writeFcLow( uint8_t data ) -> void {
	fc = (fc & 0x7f8) | (data & 7);
    
    updateFrequency();
}
// obere 8 bit der Grenzfrequenz
auto Sid::Filter::writeFcHi( uint8_t data ) -> void {
	fc = ((data << 3) & 0x7f8) | (fc & 7);
    
    updateFrequency();
}
// 4 bit - Resonanz, 4 bit - Filter / Mixer Auswahl
auto Sid::Filter::writeResFilt( uint8_t data ) -> void {
	// Resonanz für Bandpass Filter
	res = ( data >> 4 ) & 0xf;
	// Steuert für alle 4 voices ( 1 - 3 ) + externe voice ob diese in den Filter
	// oder direkt in den Mixer geleitet wird. siehe v1 - ve im Schaltkreis
	filt = data & 0xf;
	
	updateSumMix();
    updateQ();
}

// 4 bit - Lautstärke, 4 bit - voice 3 Abschaltung, filter Resultate mixen
auto Sid::Filter::writeModeVol( uint8_t data ) -> void {
	// Steuert welche Filter Ausgänge gemixt werden. Außerdem kann
	// voice 3 komplett deaktivert werden, wenn in Register 0x17
	// für voice 3 keine Filterung gewählt wird.
	mode = data & 0xf0;
	// Master volume wird nach dem Mixer / Filter angewandt
	vol = data & 0xf;
    
    updateSumMix();
}

auto Sid::Filter::updateFrequency() -> void {
    
    { // 6581
        Calculated& ca = calculated[0];
        // 'f0_dac' skaliert: 16 bit
        int Vw = Vw_bias + ca.f0_dac[fc];
		// Vorberechnung für: (Vddt - Vw)^2) / 2
		// siehe 'opamp.cpp' unter 'solveIntegrate6581
		// Normalisierung kürzt sich weg
		// Vddt - vmin - ( Vw - vmin ) = Vddt - Vw				
        Vddt_Vw_2 = unsigned(ca.kVddt - Vw) * unsigned(ca.kVddt - Vw) >> 1;
    }
        
    { // 8580
        Calculated& ca = calculated[1];
        // sklaiert: 13 + 5 = 18 bit
        int n_param = (int)(ca.tmp_n_param * 32 + 0.5);
		// n = (ucox/2k * dt/C) * w/l
		// geänderter Widerstand w/l wird mit unveränderbarer Konstante vorberechnet
    	// skaliert: 18 + 10 - 15 = 13 bit
        n_dac = (n_param * ca.f0_dac[ fc ]) >> 15;        
        
        w0 = 82355 * (fc + 1) >> 11; // reSID24
    }
}

auto Sid::Filter::updateSumMix() -> void {
	
    // Filter Eingänge: bit 0: v1 , bit 1: v2 , bit 2: v3 , bit 3: ve
	// Übernahme der voices, welche in den Filter gelangen
	sum = (enabled ? filt : 0) & voiceMask; // filter summer
    // Mixer Eingänge: bit 0: v1 , bit 1: v2 , bit 2: v3 , bit 3: ve 
    // bit 4: tief pass , bit 5: band pass , bit 6: hoch pass
    // Damit 'mode' und 'mix' deckungsgleich sind, sind
    // die 4 mode bits um 4 bits nach links geschoben.
    
    // mode & 0x70 prüft für bit 4, 5, 6 ob die Filter Ausgänge in den Mixer gelangen
    // mode & 0x80 prüft ob voice 3 in den Mixer gelangt
    // alle '0' bits in 'filt' sind Mixer Eingänge
    // wenn voice 3 deaktiviert, interessiert uns das entsprechende bit in 'filt' nicht
    // also voice 3 geht nur direkt in den Mixer, wenn bit 2 in 'filt' 0 ist und
    // wenn bit 7 in 'mode' 0 ist
    
    if (enabled) {
        mix = (mode & 0x70) | ( (~(filt | (mode & 0x80) >> 5)) & 0x0f );    
        
    } else {
        // Das ist keine Option des SID Chips, sondern im Rahmen
        // der emulation die Möglichkeit den filter unabhängig von der
        // Software zu deaktivieren.
        // voice 3 wird nur deaktivert, wenn es per Register für filter
        // und mixer deaktiviert ist, also die Software voice 3 komplett
        // deaktiviert hat.
        if ( (mode & 0x80) && !(filt & 4) )
            mix = 0xb; // alle voices außer voice 3 gehen ungefiltert in den Mixer
        else
            mix = 0xf; // alle voices gehen ungefiltert in den Mixer
    }
    
    mix &= voiceMask;

	if (sid->separateFilterInputs)
		prepareSeparate();
}

auto Sid::Filter::setType( Type type ) -> void {
    // Sid Modell auswählen
	this->type = type;
	// Werte initialisieren, für den Fall das das Sid Model zur Laufzeit
	// geändert wird.
	Vhp = VbpRes = 0;
	Vbp = Vbp_x = Vbp_vc = 0;
	Vlp = Vlp_x = Vlp_vc = 0;

	if (sid->separateFilterInputs)
		prepareSeparate();
}

// Filter kann unabhängig von der Software deakiviert werden.
auto Sid::Filter::setEnable( bool state ) -> void {
	enabled = state;
	
	updateSumMix();
}

auto Sid::Filter::setVoiceMask( uint8_t mask ) -> void {
    // Wird normalerweise dazu benuzt 've' zu deaktivieren.
    // Es können jedoch alle anderen voices ebenso deaktiviert
    // werden.
    voiceMask = 0xf0 | (mask & 0x0f);
    
    updateSumMix();
}

auto Sid::Filter::reset() -> void {
    fc = 0;
    res = 0;
    filt = 0;
    mode = 0;
    vol = 0;

    Vhp = 0;
    Vbp = Vbp_x = Vbp_vc = 0;
    Vlp = Vlp_x = Vlp_vc = 0;

    updateFrequency();
    updateQ();
    updateSumMix();
}

auto Sid::Filter::adjustFilterBias6581(int value) -> void {
    bias6581 = value;
    
    double dac_bias = (double)value / 1000.0;

	Vw_bias = int( dac_bias * calculated[0].vo_N16);
	updateFrequency();
}

auto Sid::Filter::adjustFilterBias8580(int value) -> void {
    bias8580 = value;
    
    double dac_bias = (double)value / 1000.0;    

	double Vg = 4.7975 * (dac_bias * 6./100. + 1.6);
	double Vgt = parameter[1].k * (Vg - parameter[1].Vth);
	double vmin = parameter[1].opampVoltage[0][0];

	kVgt = (int)(calculated[1].vo_N16 * (Vgt - vmin) + 0.5);
}

}
